// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"
	"io"
)

type Endpoints interface {
	// ProxyRequest forwards a request to the MCP server API with authentication headers.
	// The body parameter should contain the MCP protocol message (JSON-RPC).
	// The response body is returned as an io.ReadCloser for streaming - caller must close it.
	// HTTP errors (status >= 300) are returned as errors. MCP protocol errors (JSON-RPC
	// errors with status 200) are passed through in the response body.
	ProxyRequest(ctx context.Context, body []byte) (io.ReadCloser, error)
}
