// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"
)

type Endpoints interface {
	GetSLO(ctx context.Context, project, name string) (slo SLODetails, err error)
	GetSLOs(ctx context.Context, params GetSLOsRequest) (slos SLOListResponse, err error)
}
