// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"
)

type Endpoints interface {
	GetSLO(ctx context.Context, name, project string) (SLODetails, error)
	GetSLOList(ctx context.Context, limit int, cursor string) (SLOListResponse, error)
}
