// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"

	v1alphaSLO "github.com/nobl9/nobl9-go/manifest/v1alpha/slo"
)

type Endpoints interface {
	// CreateAnalysis creates an SLI analysis and starts data processing.
	CreateAnalysis(ctx context.Context, request CreateAnalysisRequest) (response Analysis, err error)
	// GetAnalysis returns an SLI analysis by project and name.
	GetAnalysis(ctx context.Context, project, name string) (response Analysis, err error)
	// ListAnalyses returns every SLI analysis visible to the current user.
	ListAnalyses(ctx context.Context) (response []Analysis, err error)
	// UpdateAnalysis updates the display name of an SLI analysis.
	UpdateAnalysis(ctx context.Context, name string, request UpdateAnalysisRequest) error
	// DeleteAnalysis deletes an SLI analysis by project and name.
	DeleteAnalysis(ctx context.Context, project, name string) error
	// CreateCalculation starts a calculation for an SLI analysis.
	CreateCalculation(ctx context.Context, project, name string, request CreateCalculationRequest) error
	// GetCalculation returns the error budget burn-down series for an SLI analysis.
	GetCalculation(ctx context.Context, project, name string) (response Timeseries, err error)
	// GetSummary returns the calculation summary for an SLI analysis.
	GetSummary(ctx context.Context, project, name string) (response AnalysisCalculationSummary, err error)
	// GetTimeseries returns the aggregated metric series for an SLI analysis.
	GetTimeseries(ctx context.Context, project, name string) (response AggregatedTimeseries, err error)
	// GetStats returns descriptive statistics for an SLI analysis.
	GetStats(ctx context.Context, project, name string) (response AnalysisStats, err error)
	// GetHistogram returns histogram data for an SLI analysis.
	GetHistogram(ctx context.Context, project, name string) (response AnalysisHistogram, err error)
	// GenerateSLO returns an SLO generated from an SLI analysis.
	GenerateSLO(ctx context.Context, project, name string) (response v1alphaSLO.SLO, err error)
}
