changelog:
  exclude:
    labels:
      - dependencies
    authors:
      - renovate
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug fixes 🐞
      labels:
        - bug
    - title: Fixed Vulnerabilities 💻
      labels:
        - security
