// Code generated by ifacemaker; DO NOT EDIT.

package v2

import (
	"context"
)

type Endpoints interface {
	Apply(ctx context.Context, params ApplyRequest) error
	Delete(ctx context.Context, params DeleteRequest) error
	DeleteByName(ctx context.Context, params DeleteByNameRequest) error
}
