apiVersion: n9/v1alpha
kind: Alert
metadata:
  name: silenced-alert-example
  project: default
spec:
  alertPolicy:
    name: my-alert-policy
    displayName: My Alert Policy
    project: default
  slo:
    name: my-slo
    displayName: My SLO
    project: default
  service:
    name: my-service
    displayName: My Service
    project: default
  objective:
    value: 0.99
    name: availability-objective
    displayName: Availability Objective
  severity: Medium
  status: Triggered
  triggeredMetricTime: "2024-01-15T14:00:00Z"
  triggeredClockTime: "2024-01-15T14:01:00Z"
  coolDown: 10m0s
  conditions:
  - measurement: burnRate
    value: 5.2
    alertingWindow: 30m
    lastsFor: 2m
    op: gt
    status:
      firstMetMetricTime: "2024-01-15T13:58:00Z"
  silenced:
    from: "2024-01-15T14:00:00Z"
    to: "2024-01-15T16:00:00Z"
