// Code generated by ifacemaker; DO NOT EDIT.

package v2

import (
	"context"
)

type Endpoints interface {
	// GetUsers fetches a list of [User] filtered by the provided search phrase.
	GetUsers(ctx context.Context, params GetUsersRequest) ([]*User, error)
	// GetUser fetches a user by a unique identifier, this can be either:
	//   - external id (e.g. 00u2y4e4atkzaYkXP4x8)
	//   - email (e.g. foo.bar@nobl9.com)
	//
	// It returns nil if the user was not found.
	GetUser(ctx context.Context, id string) (*User, error)
}
