// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package annotation

import (
	"fmt"
	"strings"
)

const (
	// CategoryComment is a Category of type Comment.
	CategoryComment Category = "Comment"
	// CategoryReviewNote is a Category of type ReviewNote.
	CategoryReviewNote Category = "ReviewNote"
	// CategorySloEdit is a Category of type SloEdit.
	CategorySloEdit Category = "SloEdit"
	// CategoryAlert is a Category of type Alert.
	CategoryAlert Category = "Alert"
	// CategoryAdjustment is a Category of type Adjustment.
	CategoryAdjustment Category = "Adjustment"
	// CategoryNoDataAnomaly is a Category of type NoDataAnomaly.
	CategoryNoDataAnomaly Category = "NoDataAnomaly"
	// CategoryIncrementalMismatchAnomaly is a Category of type IncrementalMismatchAnomaly.
	CategoryIncrementalMismatchAnomaly Category = "IncrementalMismatchAnomaly"
	// CategoryNoBurnAnomaly is a Category of type NoBurnAnomaly.
	CategoryNoBurnAnomaly Category = "NoBurnAnomaly"
	// CategoryConstantBurnAnomaly is a Category of type ConstantBurnAnomaly.
	CategoryConstantBurnAnomaly Category = "ConstantBurnAnomaly"
)

var ErrInvalidCategory = fmt.Errorf("not a valid Category, try [%s]", strings.Join(_CategoryNames, ", "))

var _CategoryNames = []string{
	string(CategoryComment),
	string(CategoryReviewNote),
	string(CategorySloEdit),
	string(CategoryAlert),
	string(CategoryAdjustment),
	string(CategoryNoDataAnomaly),
	string(CategoryIncrementalMismatchAnomaly),
	string(CategoryNoBurnAnomaly),
	string(CategoryConstantBurnAnomaly),
}

// CategoryNames returns a list of possible string values of Category.
func CategoryNames() []string {
	tmp := make([]string, len(_CategoryNames))
	copy(tmp, _CategoryNames)
	return tmp
}

// String implements the Stringer interface.
func (x Category) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Category) IsValid() bool {
	_, err := ParseCategory(string(x))
	return err == nil
}

var _CategoryValue = map[string]Category{
	"Comment":                    CategoryComment,
	"comment":                    CategoryComment,
	"ReviewNote":                 CategoryReviewNote,
	"reviewnote":                 CategoryReviewNote,
	"SloEdit":                    CategorySloEdit,
	"sloedit":                    CategorySloEdit,
	"Alert":                      CategoryAlert,
	"alert":                      CategoryAlert,
	"Adjustment":                 CategoryAdjustment,
	"adjustment":                 CategoryAdjustment,
	"NoDataAnomaly":              CategoryNoDataAnomaly,
	"nodataanomaly":              CategoryNoDataAnomaly,
	"IncrementalMismatchAnomaly": CategoryIncrementalMismatchAnomaly,
	"incrementalmismatchanomaly": CategoryIncrementalMismatchAnomaly,
	"NoBurnAnomaly":              CategoryNoBurnAnomaly,
	"noburnanomaly":              CategoryNoBurnAnomaly,
	"ConstantBurnAnomaly":        CategoryConstantBurnAnomaly,
	"constantburnanomaly":        CategoryConstantBurnAnomaly,
}

// ParseCategory attempts to convert a string to a Category.
func ParseCategory(name string) (Category, error) {
	if x, ok := _CategoryValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _CategoryValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Category(""), fmt.Errorf("%s is %w", name, ErrInvalidCategory)
}
