package annotation

import "slices"

//go:generate ../../../bin/go-enum --values --nocomments

// Category classifies [Annotation] based on its origin (how was it generated).
/* ENUM(
Comment
ReviewNote
SloEdit
Alert
Adjustment
NoDataAnomaly
IncrementalMismatchAnomaly
NoBurnAnomaly
ConstantBurnAnomaly
)*/
type Category string

var systemCategories = []Category{
	CategoryAlert,
	CategoryAdjustment,
	CategoryNoDataAnomaly,
	CategoryIncrementalMismatchAnomaly,
	CategoryNoBurnAnomaly,
	CategoryConstantBurnAnomaly,
}

var userCategories = []Category{
	CategoryComment,
	CategoryReviewNote,
	CategorySloEdit,
}

// GetSystemCategories returns all annotation [Category] generated by the Nobl9 platform.
func GetSystemCategories() []Category {
	return slices.Clone(systemCategories)
}

// GetUserCategories returns all annotation [Category] generated by the users.
func GetUserCategories() []Category {
	return slices.Clone(userCategories)
}
