// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package annotation

import (
	"errors"
	"fmt"
)

const (
	CategoryComment                    Category = "Comment"
	CategoryReviewNote                 Category = "ReviewNote"
	CategorySloEdit                    Category = "SloEdit"
	CategoryAlert                      Category = "Alert"
	CategoryAdjustment                 Category = "Adjustment"
	CategoryNoDataAnomaly              Category = "NoDataAnomaly"
	CategoryIncrementalMismatchAnomaly Category = "IncrementalMismatchAnomaly"
	CategoryNoBurnAnomaly              Category = "NoBurnAnomaly"
	CategoryConstantBurnAnomaly        Category = "ConstantBurnAnomaly"
	CategoryAlertSilence               Category = "AlertSilence"
)

var ErrInvalidCategory = errors.New("not a valid Category")

// CategoryValues returns a list of the values for Category
func CategoryValues() []Category {
	return []Category{
		CategoryComment,
		CategoryReviewNote,
		CategorySloEdit,
		CategoryAlert,
		CategoryAdjustment,
		CategoryNoDataAnomaly,
		CategoryIncrementalMismatchAnomaly,
		CategoryNoBurnAnomaly,
		CategoryConstantBurnAnomaly,
		CategoryAlertSilence,
	}
}

// String implements the Stringer interface.
func (x Category) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Category) IsValid() bool {
	_, err := ParseCategory(string(x))
	return err == nil
}

var _CategoryValue = map[string]Category{
	"Comment":                    CategoryComment,
	"ReviewNote":                 CategoryReviewNote,
	"SloEdit":                    CategorySloEdit,
	"Alert":                      CategoryAlert,
	"Adjustment":                 CategoryAdjustment,
	"NoDataAnomaly":              CategoryNoDataAnomaly,
	"IncrementalMismatchAnomaly": CategoryIncrementalMismatchAnomaly,
	"NoBurnAnomaly":              CategoryNoBurnAnomaly,
	"ConstantBurnAnomaly":        CategoryConstantBurnAnomaly,
	"AlertSilence":               CategoryAlertSilence,
}

// ParseCategory attempts to convert a string to a Category.
func ParseCategory(name string) (Category, error) {
	if x, ok := _CategoryValue[name]; ok {
		return x, nil
	}
	return Category(""), fmt.Errorf("%s is %w", name, ErrInvalidCategory)
}
