// Code is generated by "generate-object-impl Agent"; DO NOT EDIT.

package agent

import (
	"github.com/nobl9/nobl9-go/manifest"
	"github.com/nobl9/nobl9-go/manifest/v1alpha"
)

// Ensure interfaces are implemented.
var _ manifest.Object = Agent{}
var _ manifest.ProjectScopedObject = Agent{}
var _ v1alpha.ObjectContext = Agent{}

func (a Agent) GetVersion() manifest.Version {
	return a.APIVersion
}

func (a Agent) GetKind() manifest.Kind {
	return a.Kind
}

func (a Agent) GetName() string {
	return a.Metadata.Name
}

func (a Agent) Validate() error {
	if err := validate(a); err != nil {
		return err
	}
	return nil
}

func (a Agent) GetManifestSource() string {
	return a.ManifestSource
}

func (a Agent) SetManifestSource(src string) manifest.Object {
	a.ManifestSource = src
	return a
}

func (a Agent) GetProject() string {
	return a.Metadata.Project
}

func (a Agent) SetProject(project string) manifest.Object {
	a.Metadata.Project = project
	return a
}

func (a Agent) GetOrganization() string {
	return a.Organization
}

func (a Agent) SetOrganization(org string) manifest.Object {
	a.Organization = org
	return a
}
