apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: prometheus
  displayName: My Prometheus
  project: default
spec:
  description: Example Prometheus Agent
  prometheus:
    url: https://prometheus-service.monitoring:8080