package e2etestutils

import (
	"fmt"
	"strings"
	"testing"

	"github.com/nobl9/nobl9-go/manifest"
	"github.com/nobl9/nobl9-go/manifest/v1alpha"
	v1alphaAgent "github.com/nobl9/nobl9-go/manifest/v1alpha/agent"
	v1alphaDirect "github.com/nobl9/nobl9-go/manifest/v1alpha/direct"
	v1alphaProject "github.com/nobl9/nobl9-go/manifest/v1alpha/project"
)

// DataSourcesProject is the Project which contains all the static Data Sources
// shared between different tests and their runs.
const DataSourcesProject = "e2e-data-sources"

const objectPersistedDescription = "Object generated by end-to-end tests." +
	" This object is persisted across all tests, do not delete it."

// StaticAgents applies and returns every type of [v1alphaAgent.Agent].
// These Agents are meant to be persisted across test runs.
func StaticAgents(t *testing.T) []manifest.Object {
	t.Helper()

	agentTypes := v1alpha.DataSourceTypeValues()
	objects := make([]manifest.Object, 0, len(agentTypes)+1)
	for _, typ := range agentTypes {
		example := GetExample(t, manifest.KindAgent, FilterExamplesByDataSourceType(typ))
		agent := example.GetObject().(v1alphaAgent.Agent)
		agent.Metadata = v1alphaAgent.Metadata{
			Name:    fmt.Sprintf("e2e-agent-%s", strings.ToLower(typ.String())),
			Project: DataSourcesProject,
		}
		agent.Spec.Description = objectPersistedDescription
		objects = append(objects, agent)
	}

	V1Apply(t, []manifest.Object{getDataSourcesProject()})
	V1ApplyBatch(t, objects, 1)
	return objects
}

// StaticDirects applies and returns every type of [v1alphaDirect.Direct].
// These Directs are meant to be persisted across test runs.
func StaticDirects(t *testing.T) []manifest.Object {
	t.Helper()

	dataSourceTypes := v1alpha.DataSourceTypeValues()
	objects := make([]manifest.Object, 0, len(dataSourceTypes))
	for _, typ := range dataSourceTypes {
		if !v1alphaDirect.IsValidDirectType(typ) {
			continue
		}
		example := GetExample(t, manifest.KindDirect, FilterExamplesByDataSourceType(typ))
		direct := example.GetObject().(v1alphaDirect.Direct)
		direct.Metadata = v1alphaDirect.Metadata{
			Name:    fmt.Sprintf("e2e-direct-%s", strings.ToLower(typ.String())),
			Project: DataSourcesProject,
		}
		direct.Spec.Description = objectPersistedDescription
		objects = append(objects, direct)
	}

	V1Apply(t, []manifest.Object{getDataSourcesProject()})
	V1Apply(t, objects)
	return objects
}

func getDataSourcesProject() v1alphaProject.Project {
	return v1alphaProject.New(
		v1alphaProject.Metadata{
			Name:        DataSourcesProject,
			DisplayName: "End-to-end Data Sources",
			Labels: v1alpha.Labels{
				"origin": []string{"e2e-test"},
			},
		},
		v1alphaProject.Spec{
			Description: "This Project contains a collection of all Agent and Direct types used for end-to-end tests." +
				" This Project along with all its associated objects is meant to be persisted across test runs" +
				" in order to speed up the execution of other tests, primarily targeting SLOs.",
		},
	)
}
