package e2etestutils

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

func TestIsStaleName(t *testing.T) {
	toolName = "SDK"
	t.Cleanup(func() { toolName = "" })
	now := time.Now()
	age := func(d time.Duration) time.Time { return now.Add(-d) }

	t.Run("generated name older than max age", func(t *testing.T) {
		name := generateNameAt(age(4 * time.Hour))
		assert.True(t, IsStaleName(name, now, 3*time.Hour))
	})
	t.Run("generated name younger than max age", func(t *testing.T) {
		name := generateNameAt(age(time.Hour))
		assert.False(t, IsStaleName(name, now, 3*time.Hour))
	})
	t.Run("current GenerateName output", func(t *testing.T) {
		assert.False(t, IsStaleName(GenerateName(), now, 3*time.Hour))
		assert.True(t, IsStaleName(GenerateName(), now.Add(4*time.Hour), 3*time.Hour))
	})
	t.Run("names not generated by GenerateName", func(t *testing.T) {
		for _, name := range []string{"sdk-e2e-default", "e2e-data-sources", "other-e2e-7-1", "sdk-e2e-7-x", ""} {
			assert.False(t, IsStaleName(name, now.Add(24*time.Hour), time.Hour), name)
		}
	})
}
