// Code generated by "objectimpl RoleBinding"; DO NOT EDIT.

package rolebinding

import (
	"github.com/nobl9/govy/pkg/govy"
	"github.com/nobl9/nobl9-go/manifest"
	"github.com/nobl9/nobl9-go/manifest/v1alpha"
)

// Ensure interfaces are implemented.
var _ manifest.Object = RoleBinding{}
var _ v1alpha.ObjectContext = RoleBinding{}

func (r RoleBinding) GetVersion() manifest.Version {
	return manifest.VersionV1alpha
}

func (r RoleBinding) GetKind() manifest.Kind {
	return manifest.KindRoleBinding
}

func (r RoleBinding) GetName() string {
	return r.Metadata.Name
}

func (r RoleBinding) Validate() error {
	if err := validate(r); err != nil {
		return err
	}
	return nil
}

func (r RoleBinding) GetManifestSource() string {
	return r.ManifestSource
}

func (r RoleBinding) SetManifestSource(src string) manifest.Object {
	r.ManifestSource = src
	return r
}

func (r RoleBinding) GetOrganization() string {
	return r.Organization
}

func (r RoleBinding) SetOrganization(org string) manifest.Object {
	r.Organization = org
	return r
}

func (r RoleBinding) GetValidator() govy.Validator[RoleBinding] {
	return validator
}
