// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package rolebinding

import (
	"fmt"
	"strings"
)

const (
	// TypeProject is a Type of type Project.
	TypeProject Type = iota + 1
	// TypeOrganization is a Type of type Organization.
	TypeOrganization
)

var ErrInvalidType = fmt.Errorf("not a valid Type, try [%s]", strings.Join(_TypeNames, ", "))

const _TypeName = "ProjectOrganization"

var _TypeNames = []string{
	_TypeName[0:7],
	_TypeName[7:19],
}

// TypeNames returns a list of possible string values of Type.
func TypeNames() []string {
	tmp := make([]string, len(_TypeNames))
	copy(tmp, _TypeNames)
	return tmp
}

var _TypeMap = map[Type]string{
	TypeProject:      _TypeName[0:7],
	TypeOrganization: _TypeName[7:19],
}

// String implements the Stringer interface.
func (x Type) String() string {
	if str, ok := _TypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Type(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Type) IsValid() bool {
	_, ok := _TypeMap[x]
	return ok
}

var _TypeValue = map[string]Type{
	_TypeName[0:7]:                   TypeProject,
	strings.ToLower(_TypeName[0:7]):  TypeProject,
	_TypeName[7:19]:                  TypeOrganization,
	strings.ToLower(_TypeName[7:19]): TypeOrganization,
}

// ParseType attempts to convert a string to a Type.
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _TypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Type(0), fmt.Errorf("%s is %w", name, ErrInvalidType)
}
