//go:build e2e_test

package tests

import (
	"context"
	"fmt"
	"net/http"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/nobl9/nobl9-go/manifest"
	"github.com/nobl9/nobl9-go/manifest/v1alpha"
	v1alphaExamples "github.com/nobl9/nobl9-go/manifest/v1alpha/examples"
	v1alphaReport "github.com/nobl9/nobl9-go/manifest/v1alpha/report"
	v1alphaService "github.com/nobl9/nobl9-go/manifest/v1alpha/service"
	v1alphaSLO "github.com/nobl9/nobl9-go/manifest/v1alpha/slo"
	"github.com/nobl9/nobl9-go/sdk"
	objectsV1 "github.com/nobl9/nobl9-go/sdk/endpoints/objects/v1"
	reportsV1 "github.com/nobl9/nobl9-go/sdk/endpoints/reports/v1"
	"github.com/nobl9/nobl9-go/tests/e2etestutils"
)

func Test_Reports_V1_GetUsageSummary(t *testing.T) {
	e2etestutils.ProvisionStaticAgent(t, v1alpha.Prometheus)
	response, err := tryExecuteRequest(t, func() (reportsV1.UsageSummary, error) {
		response, err := client.Reports().V1().GetUsageSummary(t.Context())
		if err == nil && response.UsageSummary.DataSources.CurrentUsage < 1 {
			err = fmt.Errorf("usage summary does not count the test data source yet")
		}
		return response, err
	})
	require.NoError(t, err)
	assert.NotEmpty(t, response.Metadata.Tier.Name)
	_, err = time.Parse(time.RFC3339Nano, response.Metadata.GeneratedAt)
	assert.NoError(t, err)
	for name, usage := range map[string]reportsV1.Usage{
		"SLOs":                 response.UsageSummary.SLOs,
		"SLO units":            response.UsageSummary.SLOUnits,
		"composite components": response.UsageSummary.CompositeSLOComponents,
		"data sources":         response.UsageSummary.DataSources,
		"users":                response.UsageSummary.Users,
	} {
		t.Run(name, func(t *testing.T) {
			assert.GreaterOrEqual(t, usage.CurrentUsage, float64(0))
			assert.GreaterOrEqual(t, usage.PeakUsage, float64(0))
			if usage.ContractedAmount != nil {
				assert.GreaterOrEqual(t, *usage.ContractedAmount, float64(0))
			}
			if usage.QuotaStatus != nil {
				assert.Contains(t, []string{"reached", "exceeded"}, *usage.QuotaStatus)
			}
		})
	}
}

func Test_Reports_V1_ReliabilityRollup(t *testing.T) {
	report, slos := setupReportsTest(t)
	api := client.Reports().V1()
	params := reportsV1.ReliabilityRollupRequest{To: time.Now().UTC()}
	params.From = params.To.Add(-24 * time.Hour)

	saved, err := tryExecuteRequest(t, func() (reportsV1.ReliabilityRollup, error) {
		response, err := api.GetReliabilityRollup(t.Context(), report.GetName(), params)
		if err == nil && len(reportSLOs(response.ReliabilityGaugeStructure)) != len(slos) {
			err = fmt.Errorf("report does not contain all test SLOs yet")
		}
		return response, err
	})
	require.NoError(t, err)
	assertReportsRollup(t, saved, params, slos)

	adHoc := deepCopyObject(t, report)
	adHoc.Metadata.Name = e2etestutils.GenerateName()
	for _, tt := range []struct {
		name string
		get  func(context.Context, reportsV1.ReliabilityRollupRequest) (reportsV1.ReliabilityRollup, error)
	}{
		{
			name: "saved",
			get: func(ctx context.Context, request reportsV1.ReliabilityRollupRequest) (reportsV1.ReliabilityRollup, error) {
				return api.GetReliabilityRollup(ctx, report.GetName(), request)
			},
		},
		{
			name: "ad hoc",
			get: func(ctx context.Context, request reportsV1.ReliabilityRollupRequest) (reportsV1.ReliabilityRollup, error) {
				return api.GenerateReliabilityRollup(ctx, adHoc, request)
			},
		},
	} {
		t.Run(tt.name, func(t *testing.T) {
			actual, err := tt.get(t.Context(), params)
			require.NoError(t, err)
			assertReportsRollup(t, actual, params, slos)
			testReportsFilters(t, tt.get, params, slos)
			testReportsPeriods(t, tt.get, params, slos)
			testReportsInvalidRequests(t, tt.get, params)
		})
	}

	t.Run("custom hierarchy", func(t *testing.T) {
		custom := deepCopyObject(t, adHoc)
		custom.Spec.Filters = nil
		custom.Spec.ReliabilityRollup.CustomHierarchy = []v1alphaReport.HierarchyFolder{
			{
				DisplayName: "Reports root",
				Children: []v1alphaReport.HierarchyFolder{
					{DisplayName: "Zeta folder", SLOs: []v1alphaReport.HierarchySLORef{
						{Name: slos[1].GetName(), Project: slos[1].GetProject()},
					}},
					{DisplayName: "Alpha folder", SLOs: []v1alphaReport.HierarchySLORef{
						{Name: slos[0].GetName(), Project: slos[0].GetProject()},
					}},
				},
			},
		}
		request := params
		request.Sort = reportsV1.SortHierarchy
		request.Direction = reportsV1.DirectionAsc
		actual, err := api.GenerateReliabilityRollup(t.Context(), custom, request)
		require.NoError(t, err)
		assert.False(t, actual.IsAutoGenerated)
		require.Len(t, actual.ReliabilityGaugeStructure, 1)
		root := actual.ReliabilityGaugeStructure[0]
		assert.Equal(t, "Reports root", root.Metadata.DisplayName)
		require.Len(t, root.Children, 2)
		assert.Equal(t, "Zeta folder", root.Children[0].Metadata.DisplayName)
		assert.Equal(t, "Alpha folder", root.Children[1].Metadata.DisplayName)
		assert.Equal(t, []string{slos[1].GetName(), slos[0].GetName()}, reportSLONames(actual))

		request.Search = "Zeta folder"
		actual, err = api.GenerateReliabilityRollup(t.Context(), custom, request)
		require.NoError(t, err)
		assert.Equal(t, []string{slos[1].GetName()}, reportSLONames(actual))
	})

	t.Run("ad hoc report is not saved", func(t *testing.T) {
		reports, err := client.Objects().V1().GetReports(t.Context(), objectsV1.GetReportsRequest{
			Names: []string{adHoc.GetName()},
		})
		require.NoError(t, err)
		assert.Empty(t, reports)
	})
	t.Run("missing report", func(t *testing.T) {
		_, err := api.GetReliabilityRollup(t.Context(), adHoc.GetName(), params)
		assertReportsHTTPError(t, err, http.StatusNotFound)
	})
	t.Run("invalid manifest", func(t *testing.T) {
		_, err := api.GenerateReliabilityRollup(t.Context(), v1alphaReport.Report{}, params)
		assertReportsHTTPError(t, err, http.StatusBadRequest)
	})
}

func testReportsFilters(
	t *testing.T,
	get func(context.Context, reportsV1.ReliabilityRollupRequest) (reportsV1.ReliabilityRollup, error),
	params reportsV1.ReliabilityRollupRequest,
	slos []v1alphaSLO.SLO,
) {
	t.Helper()
	for _, tt := range []struct {
		name   string
		modify func(*reportsV1.ReliabilityRollupRequest)
		want   []string
	}{
		{
			"search", func(r *reportsV1.ReliabilityRollupRequest) { r.Search = slos[0].Metadata.DisplayName },
			[]string{slos[0].GetName()},
		},
		{
			"label", func(r *reportsV1.ReliabilityRollupRequest) { r.Label = "reports-test:alpha" },
			[]string{slos[0].GetName()},
		},
		{
			"label OR", func(r *reportsV1.ReliabilityRollupRequest) { r.Label = "reports-test:alpha,reports-test:zeta" },
			[]string{slos[0].GetName(), slos[1].GetName()},
		},
		{
			"label AND", func(r *reportsV1.ReliabilityRollupRequest) { r.Label = "reports-test:alpha,tool:SDK" },
			[]string{slos[0].GetName()},
		},
		{"empty search", func(r *reportsV1.ReliabilityRollupRequest) { r.Search = "unmatched" }, []string{}},
		{"healthy scores", func(r *reportsV1.ReliabilityRollupRequest) {
			r.ReliabilityScore = []reportsV1.ReliabilityScore{reportsV1.ReliabilityScoreHealthy}
		}, []string{}},
		{"multiple scores", func(r *reportsV1.ReliabilityRollupRequest) {
			r.ReliabilityScore = []reportsV1.ReliabilityScore{
				reportsV1.ReliabilityScoreNotAvailable, reportsV1.ReliabilityScoreHealthy,
			}
		}, []string{slos[0].GetName(), slos[1].GetName()}},
		{"ascending names", func(r *reportsV1.ReliabilityRollupRequest) {
			r.Sort, r.Direction = reportsV1.SortName, reportsV1.DirectionAsc
		}, []string{slos[0].GetName(), slos[1].GetName()}},
		{"descending names", func(r *reportsV1.ReliabilityRollupRequest) {
			r.Sort, r.Direction = reportsV1.SortName, reportsV1.DirectionDesc
		}, []string{slos[1].GetName(), slos[0].GetName()}},
	} {
		t.Run(tt.name, func(t *testing.T) {
			request := params
			tt.modify(&request)
			response, err := get(t.Context(), request)
			require.NoError(t, err)
			assert.Equal(t, tt.want, reportSLONames(response))
		})
	}
}

func testReportsPeriods(
	t *testing.T,
	get func(context.Context, reportsV1.ReliabilityRollupRequest) (reportsV1.ReliabilityRollup, error),
	params reportsV1.ReliabilityRollupRequest,
	slos []v1alphaSLO.SLO,
) {
	t.Helper()
	previousFrom, previousTo := params.From.Add(-24*time.Hour), params.From
	for _, comparison := range []bool{false, true} {
		t.Run(fmt.Sprintf("comparison=%t", comparison), func(t *testing.T) {
			request := params
			if comparison {
				request.CompareFrom, request.CompareTo = &previousFrom, &previousTo
			} else {
				request.PrevFrom, request.PrevTo = &previousFrom, &previousTo
			}
			response, err := get(t.Context(), request)
			require.NoError(t, err)
			assert.Equal(t, []string{slos[0].GetName(), slos[1].GetName()}, reportSLONames(response))
			assert.Nil(t, response.TotalReliabilityGauge)
		})
	}
}

func testReportsInvalidRequests(
	t *testing.T,
	get func(context.Context, reportsV1.ReliabilityRollupRequest) (reportsV1.ReliabilityRollup, error),
	params reportsV1.ReliabilityRollupRequest,
) {
	t.Helper()
	for name, modify := range map[string]func(*reportsV1.ReliabilityRollupRequest){
		"reversed range":           func(r *reportsV1.ReliabilityRollupRequest) { r.From, r.To = r.To, r.From },
		"missing previous end":     func(r *reportsV1.ReliabilityRollupRequest) { r.PrevFrom = &r.From },
		"missing previous start":   func(r *reportsV1.ReliabilityRollupRequest) { r.PrevTo = &r.To },
		"missing comparison end":   func(r *reportsV1.ReliabilityRollupRequest) { r.CompareFrom = &r.From },
		"missing comparison start": func(r *reportsV1.ReliabilityRollupRequest) { r.CompareTo = &r.To },
		"previous and comparison": func(r *reportsV1.ReliabilityRollupRequest) {
			r.PrevFrom, r.PrevTo, r.CompareFrom, r.CompareTo = &r.From, &r.To, &r.From, &r.To
		},
		"invalid score": func(r *reportsV1.ReliabilityRollupRequest) {
			r.ReliabilityScore = []reportsV1.ReliabilityScore{"invalid"}
		},
		"invalid sort":      func(r *reportsV1.ReliabilityRollupRequest) { r.Sort = "invalid" },
		"invalid direction": func(r *reportsV1.ReliabilityRollupRequest) { r.Direction = "invalid" },
	} {
		t.Run(name, func(t *testing.T) {
			request := params
			modify(&request)
			_, err := get(t.Context(), request)
			assertReportsHTTPError(t, err, http.StatusBadRequest)
		})
	}
}

func setupReportsTest(t *testing.T) (v1alphaReport.Report, []v1alphaSLO.SLO) {
	t.Helper()
	project := generateV1alphaProject(t)
	service := newV1alphaService(t, v1alphaService.Metadata{
		Name: e2etestutils.GenerateName(), Project: project.GetName(),
	})
	slos := make([]v1alphaSLO.SLO, 0, 2)
	objects := make([]manifest.Object, 0, 5)
	objects = append(objects, project, service)
	for i, name := range []string{"alpha", "zeta"} {
		slo := e2etestutils.GetExampleObject[v1alphaSLO.SLO](t, manifest.KindSLO,
			func(example v1alphaExamples.Example) bool {
				if !e2etestutils.FilterExamplesByDataSourceType(v1alpha.Prometheus)(example) {
					return false
				}
				candidate := example.GetObject().(v1alphaSLO.SLO)
				return (candidate.Spec.Objectives[0].RawMetric != nil) == (i == 0)
			})
		slo.Metadata = v1alphaSLO.Metadata{
			Name: e2etestutils.GenerateName(), DisplayName: "Reports " + name, Project: project.GetName(),
			Labels: e2etestutils.AnnotateLabels(t, v1alpha.Labels{"reports-test": {name}}),
		}
		slo.Spec.Service = service.GetName()
		slo.Spec.AlertPolicies = nil
		slo.Spec.AnomalyConfig = nil
		slo.Spec.Objectives = slo.Spec.Objectives[:1]
		slo.Spec.TimeWindows = []v1alphaSLO.TimeWindow{{Unit: "Day", Count: 7, IsRolling: true}}
		if i == 1 {
			slo.Spec.TimeWindows[0] = v1alphaSLO.TimeWindow{
				Unit: "Month", Count: 1,
				Calendar: &v1alphaSLO.Calendar{StartTime: "2024-01-01 00:00:00", TimeZone: "Europe/Warsaw"},
			}
		}
		e2etestutils.ProvisionDataSourceForSLO(t, &slo)
		slos = append(slos, slo)
		objects = append(objects, slo)
	}
	report := v1alphaReport.New(v1alphaReport.Metadata{Name: e2etestutils.GenerateName()}, v1alphaReport.Spec{
		Shared:  true,
		Filters: &v1alphaReport.Filters{Projects: []string{project.GetName()}},
		ReliabilityRollup: &v1alphaReport.ReliabilityRollupConfig{
			TimeFrame: v1alphaReport.ReliabilityRollupTimeFrame{
				Rolling:  &v1alphaReport.RollingTimeFrame{Repeat: v1alphaReport.Repeat{Unit: ptr("Week"), Count: ptr(1)}},
				TimeZone: "Europe/Warsaw",
			},
		},
	})
	objects = append(objects, report)
	t.Cleanup(func() { e2etestutils.V1Delete(t, objects) })
	e2etestutils.V1Apply(t, objects)
	return report, slos
}

func assertReportsRollup(
	t *testing.T,
	response reportsV1.ReliabilityRollup,
	params reportsV1.ReliabilityRollupRequest,
	slos []v1alphaSLO.SLO,
) {
	t.Helper()
	assert.True(t, response.IsAutoGenerated)
	assert.Equal(t, len(slos), response.TotalSLOs)
	assert.Equal(t, len(slos), response.SLOStats.NotAvailable)
	assert.Equal(t, 1, response.ServiceStats.ServiceCount)
	assert.Nil(t, response.TotalReliabilityGauge)
	assert.Nil(t, response.Summary.ReliabilityScore.Value)
	assert.Nil(t, response.Summary.ReliabilityScore.Trend)
	assert.True(t, params.From.Equal(response.Summary.RollupPeriod.Start))
	assert.True(t, params.To.Equal(response.Summary.RollupPeriod.End))
	require.Len(t, response.ReliabilityGaugeStructure, 1)
	project := response.ReliabilityGaugeStructure[0]
	assert.Equal(t, slos[0].GetProject(), project.Metadata.Name)
	require.Len(t, project.Children, 1)
	assert.Equal(t, slos[0].Spec.Service, project.Children[0].Metadata.Name)
	actual := reportSLOs(response.ReliabilityGaugeStructure)
	require.Len(t, actual, len(slos))
	for i, slo := range actual {
		expected := slos[i]
		assert.Equal(t, expected.Metadata.Name, slo.Metadata.Name)
		assert.Equal(t, expected.Metadata.DisplayName, slo.Metadata.DisplayName)
		assert.Equal(t, expected.GetProject(), slo.Metadata.Project)
		assert.Equal(t, expected.Metadata.Labels, slo.Metadata.Labels)
		assert.Equal(t, expected.Spec.TimeWindows[0].Calendar, slo.TimeWindow.Calendar)
		assert.Equal(t, expected.Spec.TimeWindows[0].IsRolling, slo.TimeWindow.IsRolling)
		assert.Equal(t, expected.Spec.TimeWindows[0].Count, slo.TimeWindow.Count)
		assert.Equal(t, expected.Spec.TimeWindows[0].Unit, slo.TimeWindow.Unit)
		assert.Nil(t, slo.ReliabilityGauge)
		require.Len(t, slo.Objectives, len(expected.Spec.Objectives))
		objective := slo.Objectives[0]
		assert.Equal(t, expected.Spec.Objectives[0].Name, objective.Name)
		assert.Equal(t, expected.Spec.Objectives[0].BudgetTarget, objective.Target)
		assert.Equal(t, expected.Spec.Objectives[0].Operator, objective.Operator)
		assert.Equal(t, expected.Spec.Objectives[0].RawMetric != nil, objective.IsRawMetric)
		assert.Nil(t, objective.ReliabilityGauge)
	}
}

func reportSLOs(folders []reportsV1.Folder) []reportsV1.SLO {
	var slos []reportsV1.SLO
	for _, folder := range folders {
		slos = append(slos, folder.SLOs...)
		slos = append(slos, reportSLOs(folder.Children)...)
	}
	return slos
}

func reportSLONames(response reportsV1.ReliabilityRollup) []string {
	slos := reportSLOs(response.ReliabilityGaugeStructure)
	names := make([]string, len(slos))
	for i, slo := range slos {
		names[i] = slo.Metadata.Name
	}
	return names
}

func assertReportsHTTPError(t *testing.T, err error, status int) {
	t.Helper()
	var httpErr *sdk.HTTPError
	require.ErrorAs(t, err, &httpErr)
	assert.Equal(t, status, httpErr.StatusCode)
}
