// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"
	"io"
)

type Endpoints interface {
	// ProxyStream proxies MCP messages between a local client (stdio) and a remote MCP server (HTTP).
	// It reads line-delimited JSON-RPC messages from input and writes responses to output.
	//
	// The MCP Streamable HTTP protocol (per spec 2025-03-26):
	//   - Each client message is sent as a separate HTTP POST request
	//   - Server responds with either JSON (application/json) or SSE (text/event-stream)
	//   - Session management via Mcp-Session-Id header
	//
	// Architecture:
	//
	//	┌──────────┐         ┌─────────────┐         ┌───────────────────┐
	//	│  Client  │◄───────►│    Proxy    │◄───────►│     MCP server    │
	//	│ (Claude) │  stdio  │   (sloctl)  │  HTTP   │  (Nobl9 platform) │
	//	└──────────┘         └─────────────┘         └───────────────────┘
	ProxyStream(ctx context.Context, input io.Reader, output io.Writer) error
}
