// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"
)

type Endpoints interface {
	StartAnalysis(ctx context.Context, params StartAnalysisRequest) (response StartAnalysisResponse, err error)
	CalculateAlertPolicy(ctx context.Context, params CalculateAlertPolicyRequest) (response CalculateAlertPolicyResponse, err error)
	GetAnalysis(ctx context.Context, params GetAnalysisRequest) (response GetAnalysisResponse, err error)
	RetryAnalysis(ctx context.Context, analysisID string) (response StartAnalysisResponse, err error)
}
