// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.4
// Revision: 239df6970e0d16b293dc7407836a48ec13170862
// Build Date: 2026-07-09T20:37:25Z
// Built By: goreleaser

package v1

import (
	"fmt"
	"strings"
)

const (
	GetSLOsSortColumnProject        GetSLOsSortColumn = "project"
	GetSLOsSortColumnService        GetSLOsSortColumn = "service"
	GetSLOsSortColumnSLO            GetSLOsSortColumn = "slo"
	GetSLOsSortColumnLastModifiedAt GetSLOsSortColumn = "lastModifiedAt"
)

var ErrInvalidGetSLOsSortColumn = fmt.Errorf("not a valid GetSLOsSortColumn, try [%s]", strings.Join(_GetSLOsSortColumnNames, ", "))

var _GetSLOsSortColumnNames = []string{
	string(GetSLOsSortColumnProject),
	string(GetSLOsSortColumnService),
	string(GetSLOsSortColumnSLO),
	string(GetSLOsSortColumnLastModifiedAt),
}

// GetSLOsSortColumnNames returns a list of possible string values of GetSLOsSortColumn.
func GetSLOsSortColumnNames() []string {
	tmp := make([]string, len(_GetSLOsSortColumnNames))
	copy(tmp, _GetSLOsSortColumnNames)
	return tmp
}

// GetSLOsSortColumnValues returns a list of the values for GetSLOsSortColumn
func GetSLOsSortColumnValues() []GetSLOsSortColumn {
	return []GetSLOsSortColumn{
		GetSLOsSortColumnProject,
		GetSLOsSortColumnService,
		GetSLOsSortColumnSLO,
		GetSLOsSortColumnLastModifiedAt,
	}
}

// String implements the Stringer interface.
func (x GetSLOsSortColumn) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x GetSLOsSortColumn) IsValid() bool {
	_, err := ParseGetSLOsSortColumn(string(x))
	return err == nil
}

var _GetSLOsSortColumnValue = map[string]GetSLOsSortColumn{
	"project":        GetSLOsSortColumnProject,
	"service":        GetSLOsSortColumnService,
	"slo":            GetSLOsSortColumnSLO,
	"lastModifiedAt": GetSLOsSortColumnLastModifiedAt,
}

// ParseGetSLOsSortColumn attempts to convert a string to a GetSLOsSortColumn.
func ParseGetSLOsSortColumn(name string) (GetSLOsSortColumn, error) {
	if x, ok := _GetSLOsSortColumnValue[name]; ok {
		return x, nil
	}
	return GetSLOsSortColumn(""), fmt.Errorf("%s is %w", name, ErrInvalidGetSLOsSortColumn)
}

const (
	GetSLOsSortDirectionAsc  GetSLOsSortDirection = "asc"
	GetSLOsSortDirectionDesc GetSLOsSortDirection = "desc"
)

var ErrInvalidGetSLOsSortDirection = fmt.Errorf("not a valid GetSLOsSortDirection, try [%s]", strings.Join(_GetSLOsSortDirectionNames, ", "))

var _GetSLOsSortDirectionNames = []string{
	string(GetSLOsSortDirectionAsc),
	string(GetSLOsSortDirectionDesc),
}

// GetSLOsSortDirectionNames returns a list of possible string values of GetSLOsSortDirection.
func GetSLOsSortDirectionNames() []string {
	tmp := make([]string, len(_GetSLOsSortDirectionNames))
	copy(tmp, _GetSLOsSortDirectionNames)
	return tmp
}

// GetSLOsSortDirectionValues returns a list of the values for GetSLOsSortDirection
func GetSLOsSortDirectionValues() []GetSLOsSortDirection {
	return []GetSLOsSortDirection{
		GetSLOsSortDirectionAsc,
		GetSLOsSortDirectionDesc,
	}
}

// String implements the Stringer interface.
func (x GetSLOsSortDirection) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x GetSLOsSortDirection) IsValid() bool {
	_, err := ParseGetSLOsSortDirection(string(x))
	return err == nil
}

var _GetSLOsSortDirectionValue = map[string]GetSLOsSortDirection{
	"asc":  GetSLOsSortDirectionAsc,
	"desc": GetSLOsSortDirectionDesc,
}

// ParseGetSLOsSortDirection attempts to convert a string to a GetSLOsSortDirection.
func ParseGetSLOsSortDirection(name string) (GetSLOsSortDirection, error) {
	if x, ok := _GetSLOsSortDirectionValue[name]; ok {
		return x, nil
	}
	return GetSLOsSortDirection(""), fmt.Errorf("%s is %w", name, ErrInvalidGetSLOsSortDirection)
}
