// Code generated by "generate-object-impl Alert"; DO NOT EDIT.

package v1alpha

import "github.com/nobl9/nobl9-go/manifest"

func (a Alert) GetVersion() string {
	return a.APIVersion
}

func (a Alert) GetKind() manifest.Kind {
	return a.Kind
}

func (a Alert) GetName() string {
	return a.Metadata.Name
}

func (a Alert) Validate() error {
	//TODO implement me
	panic("implement me")
}

func (a Alert) GetProject() string {
	return a.Metadata.Project
}

func (a Alert) SetProject(project string) Alert {
	a.Metadata.Project = project
	return a
}
