// Code generated by "generate-object-impl DataExport"; DO NOT EDIT.

package v1alpha

import "github.com/nobl9/nobl9-go/manifest"

func (d DataExport) GetVersion() string {
	return d.APIVersion
}

func (d DataExport) GetKind() manifest.Kind {
	return d.Kind
}

func (d DataExport) GetName() string {
	return d.Metadata.Name
}

func (d DataExport) Validate() error {
	return validator.Check(d)
}

func (d DataExport) GetProject() string {
	return d.Metadata.Project
}

func (d DataExport) SetProject(project string) manifest.Object {
	d.Metadata.Project = project
	return d
}

func (d DataExport) GetOrganization() string {
	return d.Organization
}

func (d DataExport) SetOrganization(org string) manifest.Object {
	d.Organization = org
	return d
}

func (d DataExport) GetManifestSource() string {
	return d.ManifestSource
}

func (d DataExport) SetManifestSource(src string) manifest.Object {
	d.ManifestSource = src
	return d
}
