// Code generated by "generate-object-impl Direct"; DO NOT EDIT.

package v1alpha

import "github.com/nobl9/nobl9-go/manifest"

// Ensure interfaces are implemented.
var _ manifest.Object = Direct{}
var _ manifest.ProjectScopedObject = Direct{}
var _ ObjectContext = Direct{}

func (d Direct) GetVersion() string {
	return d.APIVersion
}

func (d Direct) GetKind() manifest.Kind {
	return d.Kind
}

func (d Direct) GetName() string {
	return d.Metadata.Name
}

func (d Direct) Validate() error {
	return validator.Check(d)
}

func (d Direct) GetProject() string {
	return d.Metadata.Project
}

func (d Direct) SetProject(project string) manifest.Object {
	d.Metadata.Project = project
	return d
}

func (d Direct) GetOrganization() string {
	return d.Organization
}

func (d Direct) SetOrganization(org string) manifest.Object {
	d.Organization = org
	return d
}

func (d Direct) GetManifestSource() string {
	return d.ManifestSource
}

func (d Direct) SetManifestSource(src string) manifest.Object {
	d.ManifestSource = src
	return d
}
