// Code generated by "generate-object-impl Project"; DO NOT EDIT.

package v1alpha

import "github.com/nobl9/nobl9-go/manifest"

func (p Project) GetVersion() string {
	return p.APIVersion
}

func (p Project) GetKind() manifest.Kind {
	return p.Kind
}

func (p Project) GetName() string {
	return p.Metadata.Name
}

func (p Project) Validate() error {
	//TODO implement me
	panic("implement me")
}

func (p Project) GetOrganization() string {
	return p.Organization
}

func (p Project) SetOrganization(org string) manifest.Object {
	p.Organization = org
	return p
}

func (p Project) GetManifestSource() string {
	return p.ManifestSource
}

func (p Project) SetManifestSource(src string) manifest.Object {
	p.ManifestSource = src
	return p
}
