// Code generated by "generate-object-impl UserGroup"; DO NOT EDIT.

package v1alpha

import "github.com/nobl9/nobl9-go/manifest"

func (u UserGroup) GetVersion() string {
	return u.APIVersion
}

func (u UserGroup) GetKind() manifest.Kind {
	return u.Kind
}

func (u UserGroup) GetName() string {
	return u.Metadata.Name
}

func (u UserGroup) Validate() error {
	return validator.Check(u)
}

func (u UserGroup) GetOrganization() string {
	return u.Organization
}

func (u UserGroup) SetOrganization(org string) manifest.Object {
	u.Organization = org
	return u
}

func (u UserGroup) GetManifestSource() string {
	return u.ManifestSource
}

func (u UserGroup) SetManifestSource(src string) manifest.Object {
	u.ManifestSource = src
	return u
}
