apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: azure-prometheus
  displayName: Azure Prometheus Direct
  project: default
  annotations:
    area: latency
    env: prod
    region: us
    team: sales
spec:
  description: Example Azure Prometheus Direct
  releaseChannel: beta
  azurePrometheus:
    url: https://prod-app.azuremonitor.com
    tenantId: 5cdecca3-c2c5-4072-89dd-5555faf05202
    clientId: 70747025-9367-41a5-98f1-59b18b5793c3
    clientSecret: "[secret]"
  historicalDataRetrieval:
    maxDuration:
      value: 30
      unit: Day
    defaultDuration:
      value: 15
      unit: Day
  queryDelay:
    value: 1
    unit: Second
