apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: cloud-watch
  displayName: CloudWatch Direct
  project: default
spec:
  description: Example CloudWatch Direct
  releaseChannel: stable
  cloudWatch:
    roleARN: arn:aws:iam::123456578901:role/awsCrossAccountProdCloudwatch-prod-app
  historicalDataRetrieval:
    maxDuration:
      value: 15
      unit: Day
    defaultDuration:
      value: 7
      unit: Day
    triggeredByCreation:
      value: 7
      unit: Day
    triggeredByEdit:
      value: 7
      unit: Day
  queryDelay:
    value: 2
    unit: Minute
