apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: google-cloud-monitoring
  displayName: Google Cloud Monitoring Direct
  project: default
  annotations:
    area: latency
    env: prod
    region: us
    team: sales
spec:
  description: Example Google Cloud Monitoring Direct
  releaseChannel: beta
  gcm:
    serviceAccountKey: "{\n  \"type\": \"service_account\",\n  \"project_id\": \"prod-app\",\n  \"private_key_id\": \"669180ba44964eddba9e2f6623721381\",\n  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nSECRET_KEY_GOES_HERE\\n-----END PRIVATE KEY-----\\n\",\n  \"client_email\": \"nobl9@nobl9.iam.gserviceaccount.com\",\n  \"client_id\": \"eddba9e2f66237213812\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/nobl9%40nobl9.iam.gserviceaccount.com\"\n}"
    step: 15s
  historicalDataRetrieval:
    maxDuration:
      value: 30
      unit: Day
    defaultDuration:
      value: 15
      unit: Day
  queryDelay:
    value: 3
    unit: Minute
