apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: honeycomb
  displayName: Honeycomb Direct
  project: default
spec:
  description: Example Honeycomb Direct
  releaseChannel: beta
  honeycomb:
    apiKey: "[secret]"
  historicalDataRetrieval:
    maxDuration:
      value: 7
      unit: Day
    defaultDuration:
      value: 3
      unit: Day
    triggeredByCreation:
      value: 3
      unit: Day
    triggeredByEdit:
      value: 3
      unit: Day
  queryDelay:
    value: 6
    unit: Minute
