apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: logic-monitor
  displayName: LogicMonitor Direct
  project: default
spec:
  description: Example LogicMonitor Direct
  releaseChannel: beta
  logicMonitor:
    account: my-account-name
    accessId: 9xA2BssShK21ld9LoOYu
    accessKey: "[secret]"
  historicalDataRetrieval:
    maxDuration:
      value: 30
      unit: Day
    defaultDuration:
      value: 15
      unit: Day
    triggeredBySloCreation:
      value: 15
      unit: Day
    triggeredBySloEdit:
      value: 15
      unit: Day
  queryDelay:
    value: 3
    unit: Minute
