apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: logic-monitor
  displayName: LogicMonitor Direct
  project: default
spec:
  description: Example LogicMonitor Direct
  releaseChannel: stable
  logicMonitor:
    account: myaccountname
    accessId: 9xA2BssShK21ld9LoOYu
    accessKey: "[secret]"
  queryDelay:
    duration:
      value: 3
      unit: Minute
