apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: splunk
  displayName: Splunk Direct
  project: default
spec:
  description: Example Splunk Direct
  releaseChannel: stable
  splunk:
    url: https://splunk.my-org.com/services
    accessToken: "[secret]"
  historicalDataRetrieval:
    maxDuration:
      value: 30
      unit: Day
    defaultDuration:
      value: 15
      unit: Day
  queryDelay:
    duration:
      value: 6
      unit: Minute
