apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: splunk-observability
  displayName: Splunk Observability Direct
  project: default
  annotations:
    area: latency
    env: prod
    region: us
    team: sales
spec:
  description: Example Splunk Observability Direct
  releaseChannel: alpha
  splunkObservability:
    realm: us1
    accessToken: "[secret]"
  queryDelay:
    value: 6
    unit: Minute
