apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: thousand-eyes
  displayName: ThousandEyes Direct
  project: default
  annotations:
    area: latency
    env: prod
    region: us
    team: sales
spec:
  description: Example ThousandEyes Direct
  releaseChannel: stable
  thousandEyes:
    oauthBearerToken: "[secret]"
  queryDelay:
    value: 2
    unit: Minute
