apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: amazon-prometheus
  displayName: Amazon Prometheus Agent
  project: default
spec:
  description: Example Amazon Prometheus Agent
  releaseChannel: stable
  amazonPrometheus:
    url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-f49ecf99-6dfa-4b00-9f94-a50b10a3010b
    region: us-east-1
  historicalDataRetrieval:
    maxDuration:
      value: 30
      unit: Day
    defaultDuration:
      value: 15
      unit: Day
    triggeredBySloCreation:
      value: 15
      unit: Day
    triggeredBySloEdit:
      value: 15
      unit: Day
  queryDelay:
    value: 1
    unit: Second
