apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: azure-monitor
  displayName: Azure Monitor Agent
  project: default
spec:
  description: Example Azure Monitor Agent
  releaseChannel: stable
  azureMonitor:
    tenantId: 5cdecca3-c2c5-4072-89dd-5555faf05202
  historicalDataRetrieval:
    maxDuration:
      value: 30
      unit: Day
    defaultDuration:
      value: 15
      unit: Day
  queryDelay:
    duration:
      value: 6
      unit: Minute
