apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: cloud-watch
  displayName: CloudWatch Agent
  project: default
spec:
  description: Example CloudWatch Agent
  releaseChannel: beta
  cloudWatch: {}
  historicalDataRetrieval:
    maxDuration:
      value: 15
      unit: Day
    defaultDuration:
      value: 7
      unit: Day
  queryDelay:
    value: 2
    unit: Minute
