apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: elasticsearch
  displayName: Elasticsearch Agent
  project: default
spec:
  description: Example Elasticsearch Agent
  releaseChannel: stable
  elasticsearch:
    url: http://elasticsearch-main.elasticsearch:9200
  queryDelay:
    duration:
      value: 2
      unit: Minute
