apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: google-cloud-monitoring
  displayName: Google Cloud Monitoring Agent
  project: default
  annotations:
    area: latency
    env: prod
    region: us
    team: sales
spec:
  description: Example Google Cloud Monitoring Agent
  releaseChannel: beta
  gcm:
    step: 15s
  historicalDataRetrieval:
    maxDuration:
      value: 30
      unit: Day
    defaultDuration:
      value: 15
      unit: Day
  queryDelay:
    value: 3
    unit: Minute
