apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: honeycomb
  displayName: Honeycomb Agent
  project: default
spec:
  description: Example Honeycomb Agent
  releaseChannel: beta
  honeycomb: {}
  historicalDataRetrieval:
    maxDuration:
      value: 7
      unit: Day
    defaultDuration:
      value: 3
      unit: Day
    triggeredByCreation:
      value: 3
      unit: Day
    triggeredByEdit:
      value: 3
      unit: Day
  queryDelay:
    value: 6
    unit: Minute
