apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: logic-monitor
  displayName: LogicMonitor Agent
  project: default
spec:
  description: Example LogicMonitor Agent
  releaseChannel: stable
  logicMonitor:
    account: my-account-name
  queryDelay:
    duration:
      value: 3
      unit: Minute
