apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: logic-monitor
  displayName: LogicMonitor Agent
  project: default
spec:
  description: Example LogicMonitor Agent
  releaseChannel: beta
  logicMonitor:
    account: my-account-name
  historicalDataRetrieval:
    maxDuration:
      value: 30
      unit: Day
    defaultDuration:
      value: 15
      unit: Day
    triggeredByCreation:
      value: 15
      unit: Day
    triggeredByEdit:
      value: 15
      unit: Day
  queryDelay:
    value: 3
    unit: Minute
