apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: pingdom
  displayName: Pingdom Agent
  project: default
spec:
  description: Example Pingdom Agent
  releaseChannel: stable
  pingdom: {}
  queryDelay:
    duration:
      value: 2
      unit: Minute
