apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: thousandeyes
  displayName: ThousandEyes Agent
  project: default
spec:
  description: Example ThousandEyes Agent
  releaseChannel: stable
  thousandEyes: {}
  queryDelay:
    duration:
      value: 2
      unit: Minute
