apiVersion: n9/v1alpha
kind: Agent
metadata:
  name: thousand-eyes
  displayName: ThousandEyes Agent
  project: default
  annotations:
    area: latency
    env: prod
    region: us
    team: sales
spec:
  description: Example ThousandEyes Agent
  releaseChannel: stable
  thousandEyes: {}
  queryDelay:
    value: 2
    unit: Minute
