apiVersion: n9/v1alpha
kind: BudgetAdjustment
metadata:
  name: monthly-deployment-adjustment
  displayName: Monthly deployment adjustment
spec:
  description: Adjustment for deployment happening monthly on the first Tuesday of each month for 1 hour
  firstEventStart: 2024-01-01T12:00:00Z
  duration: 1h
  rrule: FREQ=MONTHLY;INTERVAL=1;BYDAY=1TU
  filters:
    slos:
    - name: api-server-latency
      project: default
    - name: api-server-uptime
      project: default
    - name: proxy-throughput
      project: proxy
