apiVersion: n9/v1alpha
kind: BudgetAdjustment
metadata:
  name: exclude-sunday
  displayName: Exclude sunday
spec:
  description: optional description
  firstEventStart: 2024-01-11T00:00:00Z
  duration: 24h
  rrule: FREQ=WEEKLY;INTERVAL=1;BYDAY=SU
  filters:
    slos:
      - name: slo-name
        project: project
      - name: slo-name2
        project: project
      - name: slo-name3
        project: project3