apiVersion: n9/v1alpha
kind: Service
metadata:
    name: my-service
    displayName: My Service
    project: default
    labels:
        team: [ green, orange ]
        region: [ eu-central-1 ]
spec:
    description: Example Service
