# Metric type: bad over total
# Budgeting method: Occurrences
# Time window type: Calendar
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Occurrences
    objectives:
    - displayName: Good response (200)
      value: 1.0
      name: ok
      target: 0.95
      countMetrics:
        incremental: true
        good:
          azurePrometheus:
            promql: sum(api_server_requests_total{code="5xx"})
        total:
          azurePrometheus:
            promql: sum(api_server_requests_total{})
      primary: true
    service: api-server
    timeWindows:
    - unit: Month
      count: 1
      isRolling: false
      calendar:
        startTime: 2022-12-01 00:00:00
        timeZone: UTC
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: bad over total
# Budgeting method: Occurrences
# Time window type: Rolling
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Occurrences
    objectives:
    - displayName: Good response (200)
      value: 1.0
      name: ok
      target: 0.95
      countMetrics:
        incremental: true
        good:
          azurePrometheus:
            promql: sum(api_server_requests_total{code="5xx"})
        total:
          azurePrometheus:
            promql: sum(api_server_requests_total{})
      primary: true
    service: api-server
    timeWindows:
    - unit: Hour
      count: 1
      isRolling: true
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: bad over total
# Budgeting method: Timeslices
# Time window type: Calendar
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Timeslices
    objectives:
    - displayName: Good response (200)
      value: 1.0
      name: ok
      target: 0.95
      timeSliceTarget: 0.9
      countMetrics:
        incremental: true
        good:
          azurePrometheus:
            promql: sum(api_server_requests_total{code="5xx"})
        total:
          azurePrometheus:
            promql: sum(api_server_requests_total{})
      primary: true
    service: api-server
    timeWindows:
    - unit: Month
      count: 1
      isRolling: false
      calendar:
        startTime: 2022-12-01 00:00:00
        timeZone: UTC
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: bad over total
# Budgeting method: Timeslices
# Time window type: Rolling
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Timeslices
    objectives:
    - displayName: Good response (200)
      value: 1.0
      name: ok
      target: 0.95
      timeSliceTarget: 0.9
      countMetrics:
        incremental: true
        good:
          azurePrometheus:
            promql: sum(api_server_requests_total{code="5xx"})
        total:
          azurePrometheus:
            promql: sum(api_server_requests_total{})
      primary: true
    service: api-server
    timeWindows:
    - unit: Hour
      count: 1
      isRolling: true
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: good over total
# Budgeting method: Occurrences
# Time window type: Calendar
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Occurrences
    objectives:
    - displayName: Good response (200)
      value: 1.0
      name: ok
      target: 0.95
      countMetrics:
        incremental: true
        good:
          azurePrometheus:
            promql: sum(api_server_requests_total{code="2xx"})
        total:
          azurePrometheus:
            promql: sum(api_server_requests_total{})
      primary: true
    service: api-server
    timeWindows:
    - unit: Month
      count: 1
      isRolling: false
      calendar:
        startTime: 2022-12-01 00:00:00
        timeZone: UTC
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: good over total
# Budgeting method: Occurrences
# Time window type: Rolling
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Occurrences
    objectives:
    - displayName: Good response (200)
      value: 1.0
      name: ok
      target: 0.95
      countMetrics:
        incremental: true
        good:
          azurePrometheus:
            promql: sum(api_server_requests_total{code="2xx"})
        total:
          azurePrometheus:
            promql: sum(api_server_requests_total{})
      primary: true
    service: api-server
    timeWindows:
    - unit: Hour
      count: 1
      isRolling: true
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: good over total
# Budgeting method: Timeslices
# Time window type: Calendar
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Timeslices
    objectives:
    - displayName: Good response (200)
      value: 1.0
      name: ok
      target: 0.95
      timeSliceTarget: 0.9
      countMetrics:
        incremental: true
        good:
          azurePrometheus:
            promql: sum(api_server_requests_total{code="2xx"})
        total:
          azurePrometheus:
            promql: sum(api_server_requests_total{})
      primary: true
    service: api-server
    timeWindows:
    - unit: Month
      count: 1
      isRolling: false
      calendar:
        startTime: 2022-12-01 00:00:00
        timeZone: UTC
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: good over total
# Budgeting method: Timeslices
# Time window type: Rolling
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Timeslices
    objectives:
    - displayName: Good response (200)
      value: 1.0
      name: ok
      target: 0.95
      timeSliceTarget: 0.9
      countMetrics:
        incremental: true
        good:
          azurePrometheus:
            promql: sum(api_server_requests_total{code="2xx"})
        total:
          azurePrometheus:
            promql: sum(api_server_requests_total{})
      primary: true
    service: api-server
    timeWindows:
    - unit: Hour
      count: 1
      isRolling: true
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: threshold
# Budgeting method: Occurrences
# Time window type: Calendar
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Occurrences
    objectives:
    - displayName: Good response (200)
      value: 200.0
      name: ok
      target: 0.95
      rawMetric:
        query:
          azurePrometheus:
            promql: |-
              sum((rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[30m])
              - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource="cpu"}))
              * -1 >0)
      op: lte
      primary: true
    service: api-server
    timeWindows:
    - unit: Month
      count: 1
      isRolling: false
      calendar:
        startTime: 2022-12-01 00:00:00
        timeZone: UTC
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: threshold
# Budgeting method: Occurrences
# Time window type: Rolling
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Occurrences
    objectives:
    - displayName: Good response (200)
      value: 200.0
      name: ok
      target: 0.95
      rawMetric:
        query:
          azurePrometheus:
            promql: |-
              sum((rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[30m])
              - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource="cpu"}))
              * -1 >0)
      op: lte
      primary: true
    service: api-server
    timeWindows:
    - unit: Hour
      count: 1
      isRolling: true
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: threshold
# Budgeting method: Timeslices
# Time window type: Calendar
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Timeslices
    objectives:
    - displayName: Good response (200)
      value: 200.0
      name: ok
      target: 0.95
      timeSliceTarget: 0.9
      rawMetric:
        query:
          azurePrometheus:
            promql: |-
              sum((rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[30m])
              - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource="cpu"}))
              * -1 >0)
      op: lte
      primary: true
    service: api-server
    timeWindows:
    - unit: Month
      count: 1
      isRolling: false
      calendar:
        startTime: 2022-12-01 00:00:00
        timeZone: UTC
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
# Metric type: threshold
# Budgeting method: Timeslices
# Time window type: Rolling
- apiVersion: n9/v1alpha
  kind: SLO
  metadata:
    name: api-server-slo
    displayName: API Server SLO
    project: default
    labels:
      area:
      - latency
      - slow-check
      env:
      - prod
      - dev
      region:
      - us
      - eu
      team:
      - green
      - sales
    annotations:
      area: latency
      env: prod
      region: us
      team: sales
  spec:
    description: Example Azure Prometheus SLO
    indicator:
      metricSource:
        name: azure-prometheus
        project: default
        kind: Agent
    budgetingMethod: Timeslices
    objectives:
    - displayName: Good response (200)
      value: 200.0
      name: ok
      target: 0.95
      timeSliceTarget: 0.9
      rawMetric:
        query:
          azurePrometheus:
            promql: |-
              sum((rate(container_cpu_usage_seconds_total{container!="POD",container!=""}[30m])
              - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource="cpu"}))
              * -1 >0)
      op: lte
      primary: true
    service: api-server
    timeWindows:
    - unit: Hour
      count: 1
      isRolling: true
    alertPolicies:
    - fast-burn-5x-for-last-10m
    attachments:
    - url: https://docs.nobl9.com
      displayName: Nobl9 Documentation
    anomalyConfig:
      noData:
        alertMethods:
        - name: slack-notification
          project: default
