apiVersion: n9/v1alpha
kind: AlertMethod
metadata:
  name: email
  displayName: Email Alert Method
  project: default
spec:
  description: Example Email Alert Method
  email:
    to:
    - alerts-tests@nobl9.com
    cc:
    - alerts-tests+cc@nobl9.com
    bcc:
    - alerts-tests+bcc@nobl9.com
    subject: Your SLO $slo_name needs attention!
    body: "$alert_policy_name has triggered with the following conditions:\n  $alert_policy_conditions[]\n  Time: $timestamp\n  Severity: $severity\n  Project: $project_name\n  Service: $service_name\n  Organization: $organization"
