apiVersion: n9/v1alpha
kind: AlertMethod
metadata:
  name: email
  displayName: Email Alert Method
  project: default
spec:
  description: Example Email Alert Method
  email:
    to:
    - alerts-tests@nobl9.com
    cc:
    - alerts-tests+cc@nobl9.com
    bcc:
    - alerts-tests+bcc@nobl9.com
