// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.4
// Revision: 239df6970e0d16b293dc7407836a48ec13170862
// Build Date: 2026-07-09T20:37:25Z
// Built By: goreleaser

package slo

import (
	"fmt"
	"strings"
)

const (
	// ComponentAggregationMethodReliability is a ComponentAggregationMethod of type Reliability.
	ComponentAggregationMethodReliability ComponentAggregationMethod = "Reliability"
	// ComponentAggregationMethodErrorBudgetState is a ComponentAggregationMethod of type ErrorBudgetState.
	ComponentAggregationMethodErrorBudgetState ComponentAggregationMethod = "ErrorBudgetState"
)

var ErrInvalidComponentAggregationMethod = fmt.Errorf("not a valid ComponentAggregationMethod, try [%s]", strings.Join(_ComponentAggregationMethodNames, ", "))

var _ComponentAggregationMethodNames = []string{
	string(ComponentAggregationMethodReliability),
	string(ComponentAggregationMethodErrorBudgetState),
}

// ComponentAggregationMethodNames returns a list of possible string values of ComponentAggregationMethod.
func ComponentAggregationMethodNames() []string {
	tmp := make([]string, len(_ComponentAggregationMethodNames))
	copy(tmp, _ComponentAggregationMethodNames)
	return tmp
}

// ComponentAggregationMethodValues returns a list of the values for ComponentAggregationMethod
func ComponentAggregationMethodValues() []ComponentAggregationMethod {
	return []ComponentAggregationMethod{
		ComponentAggregationMethodReliability,
		ComponentAggregationMethodErrorBudgetState,
	}
}

// String implements the Stringer interface.
func (x ComponentAggregationMethod) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ComponentAggregationMethod) IsValid() bool {
	_, err := ParseComponentAggregationMethod(string(x))
	return err == nil
}

var _ComponentAggregationMethodValue = map[string]ComponentAggregationMethod{
	"Reliability":      ComponentAggregationMethodReliability,
	"reliability":      ComponentAggregationMethodReliability,
	"ErrorBudgetState": ComponentAggregationMethodErrorBudgetState,
	"errorbudgetstate": ComponentAggregationMethodErrorBudgetState,
}

// ParseComponentAggregationMethod attempts to convert a string to a ComponentAggregationMethod.
func ParseComponentAggregationMethod(name string) (ComponentAggregationMethod, error) {
	if x, ok := _ComponentAggregationMethodValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ComponentAggregationMethodValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ComponentAggregationMethod(""), fmt.Errorf("%s is %w", name, ErrInvalidComponentAggregationMethod)
}
