apiVersion: n9/v1alpha
kind: SLO
metadata:
  name: my-slo
  displayName: My SLO
  project: default
  labels:
    team: [ green, orange ]
    region: [ eu-central-1 ]
spec:
  description: Example slo
  alertPolicies: [ ]
  attachments:
    - displayName: Grafana dashboard
      url: https://loki.my-org.dev/grafana/d/nd3S__Knz/pod-restarts?orgId=1&from=now-6h&to=now&viewPanel=6
  budgetingMethod: Occurrences
  description: "Counts ratio between good and total number of http requests"
  indicator:
    metricSource:
      kind: Agent
      name: prometheus
      project: default
  objectives:
    - countMetrics:
        good:
          prometheus:
            promql: sum(rate(prometheus_http_requests_total{code=~"^2.*"}[1h]))
        incremental: false
        total:
          prometheus:
            promql: sum(rate(prometheus_http_requests_total[1h]))
      name: good
      displayName: Good
      target: 0.9
      value: 1
  service: prometheus
  timeWindows:
    - count: 1
      isRolling: true
      unit: Day
