// Code is generated by "generate-object-impl AlertPolicy"; DO NOT EDIT.

package alertpolicy

import (
	"github.com/nobl9/nobl9-go/manifest"
	"github.com/nobl9/nobl9-go/manifest/v1alpha"
)

// Ensure interfaces are implemented.
var _ manifest.Object = AlertPolicy{}
var _ manifest.ProjectScopedObject = AlertPolicy{}
var _ v1alpha.ObjectContext = AlertPolicy{}

func (a AlertPolicy) GetVersion() manifest.Version {
	return a.APIVersion
}

func (a AlertPolicy) GetKind() manifest.Kind {
	return a.Kind
}

func (a AlertPolicy) GetName() string {
	return a.Metadata.Name
}

func (a AlertPolicy) Validate() error {
	if err := validate(a); err != nil {
		return err
	}
	return nil
}

func (a AlertPolicy) GetManifestSource() string {
	return a.ManifestSource
}

func (a AlertPolicy) SetManifestSource(src string) manifest.Object {
	a.ManifestSource = src
	return a
}

func (a AlertPolicy) GetProject() string {
	return a.Metadata.Project
}

func (a AlertPolicy) SetProject(project string) manifest.Object {
	a.Metadata.Project = project
	return a
}

func (a AlertPolicy) GetOrganization() string {
	return a.Organization
}

func (a AlertPolicy) SetOrganization(org string) manifest.Object {
	a.Organization = org
	return a
}
