// Code generated by go-enum DO NOT EDIT.
// Version: 0.5.6
// Revision: 97611fddaa414f53713597918c5e954646cb8623
// Build Date: 2023-03-26T21:38:06Z
// Built By: goreleaser

package manifest

import (
	"fmt"
	"strings"
)

const (
	// RawObjectFormatJSON is a ObjectFormat of type JSON.
	RawObjectFormatJSON ObjectFormat = iota + 1
	// RawObjectFormatYAML is a ObjectFormat of type YAML.
	RawObjectFormatYAML
)

var ErrInvalidRawObjectFormat = fmt.Errorf("not a valid ObjectFormat, try [%s]", strings.Join(_RawObjectFormatNames, ", "))

const _RawObjectFormatName = "JSONYAML"

var _RawObjectFormatNames = []string{
	_RawObjectFormatName[0:4],
	_RawObjectFormatName[4:8],
}

// RawObjectFormatNames returns a list of possible string values of ObjectFormat.
func RawObjectFormatNames() []string {
	tmp := make([]string, len(_RawObjectFormatNames))
	copy(tmp, _RawObjectFormatNames)
	return tmp
}

var _RawObjectFormatMap = map[ObjectFormat]string{
	RawObjectFormatJSON: _RawObjectFormatName[0:4],
	RawObjectFormatYAML: _RawObjectFormatName[4:8],
}

// String implements the Stringer interface.
func (x ObjectFormat) String() string {
	if str, ok := _RawObjectFormatMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ObjectFormat(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ObjectFormat) IsValid() bool {
	_, ok := _RawObjectFormatMap[x]
	return ok
}

var _RawObjectFormatValue = map[string]ObjectFormat{
	_RawObjectFormatName[0:4]: RawObjectFormatJSON,
	_RawObjectFormatName[4:8]: RawObjectFormatYAML,
}

// ParseRawObjectFormat attempts to convert a string to a ObjectFormat.
func ParseRawObjectFormat(name string) (ObjectFormat, error) {
	if x, ok := _RawObjectFormatValue[name]; ok {
		return x, nil
	}
	return ObjectFormat(0), fmt.Errorf("%s is %w", name, ErrInvalidRawObjectFormat)
}
