// Code generated by "kindgen"; DO NOT EDIT.

package manifest

// ProjectScopedKinds returns all the [Kind] instances which belong to a specific project.
func ProjectScopedKinds() []Kind {
	return []Kind{
		KindAgent,
		KindAlert,
		KindAlertMethod,
		KindAlertPolicy,
		KindAlertSilence,
		KindAnnotation,
		KindDataExport,
		KindDirect,
		KindSLO,
		KindService,
	}
}
