// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"
)

type Endpoints interface {
	// GetStatus returns the organization's status page component tree, with each
	// component's computed status and any ongoing disruption impacting it.
	GetStatus(ctx context.Context) (response GetStatusResponse, err error)
	// ListDisruptions returns the organization's status page disruptions.
	ListDisruptions(ctx context.Context, params ListDisruptionsRequest) (response ListDisruptionsResponse, err error)
}
