// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"
)

type Endpoints interface {
	GetDataExportIAMRoleIDs(ctx context.Context) (*IAMRoleIDs, error)
	GetDirectIAMRoleIDs(ctx context.Context, project, directName string) (*IAMRoleIDs, error)
	// GetAgentCredentials retrieves manifest.KindAgent credentials.
	GetAgentCredentials(ctx context.Context, project, agentsName string) (creds M2MAppCredentials, err error)
}
