apiVersion: n9/v1alpha
kind: Direct
metadata:
  name: datadog
  displayName: My Datadog
  project: default
spec:
  description: Example Datadog Direct
  datadog:
    site: com
    apiKey: secret
    applicationKey: secret
