@startuml
'https://plantuml.com/activity-diagram-beta

start
:ReadConfig;
:Read ConfigOption;
:Read env variables;
if (NO_CONFIG_FILE) then (true)
 label sp_lab0
else (false)
  if (Config file exists) then (true)
    label sp_lab0
  else (false)
    :create default config file;
    label sp_lab0
  endif
  label read_conf_file
  :Read config file;
endif

repeat
  if (ConfigOption) then (use)
  (not set) elseif (Env variable) then (use)
  (not set) elseif (Config file option) then (use)
  (not set) elseif (Has default value) then (use)
  else (not set)
    :no value;
  endif
repeat while (More config options?) is (yes)

:Return Config;
stop

@enduml
