// Code generated by "stringer -trimprefix=Kind -type=Kind"; DO NOT EDIT.

package sdk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindSLO-1]
	_ = x[KindService-2]
	_ = x[KindAgent-3]
	_ = x[KindAlertPolicy-4]
	_ = x[KindAlertSilence-5]
	_ = x[KindAlert-6]
	_ = x[KindProject-7]
	_ = x[KindAlertMethod-8]
	_ = x[KindMetricSource-9]
	_ = x[KindDirect-10]
	_ = x[KindDataExport-11]
	_ = x[KindUsageSummary-12]
	_ = x[KindRoleBinding-13]
	_ = x[KindSLOErrorBudgetStatus-14]
	_ = x[KindAnnotation-15]
	_ = x[KindGroup-16]
}

const _Kind_name = "SLOServiceAgentAlertPolicyAlertSilenceAlertProjectAlertMethodMetricSourceDirectDataExportUsageSummaryRoleBindingSLOErrorBudgetStatusAnnotationGroup"

var _Kind_index = [...]uint8{0, 3, 10, 15, 26, 38, 43, 50, 61, 73, 79, 89, 101, 112, 132, 142, 147}

func (i Kind) String() string {
	i -= 1
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
