// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package v1

import (
	"fmt"

	"github.com/pkg/errors"
)

const (
	DurationUnitMinute DurationUnit = "Minute"
	DurationUnitHour   DurationUnit = "Hour"
	DurationUnitDay    DurationUnit = "Day"
)

var ErrInvalidDurationUnit = errors.New("not a valid DurationUnit")

// DurationUnitValues returns a list of the values for DurationUnit
func DurationUnitValues() []DurationUnit {
	return []DurationUnit{
		DurationUnitMinute,
		DurationUnitHour,
		DurationUnitDay,
	}
}

// String implements the Stringer interface.
func (x DurationUnit) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DurationUnit) IsValid() bool {
	_, err := ParseDurationUnit(string(x))
	return err == nil
}

var _DurationUnitValue = map[string]DurationUnit{
	"Minute": DurationUnitMinute,
	"Hour":   DurationUnitHour,
	"Day":    DurationUnitDay,
}

// ParseDurationUnit attempts to convert a string to a DurationUnit.
func ParseDurationUnit(name string) (DurationUnit, error) {
	if x, ok := _DurationUnitValue[name]; ok {
		return x, nil
	}
	return DurationUnit(""), fmt.Errorf("%s is %w", name, ErrInvalidDurationUnit)
}

const (
	ReplayAvailabilityReasonDatasourceTypeInvalid              ReplayAvailabilityReason = "datasource_type_invalid"
	ReplayAvailabilityReasonProjectDoesNotExist                ReplayAvailabilityReason = "project_does_not_exist"
	ReplayAvailabilityReasonDataSourceDoesNotExist             ReplayAvailabilityReason = "data_source_does_not_exist"
	ReplayAvailabilityReasonIntegrationDoesNotSupportReplay    ReplayAvailabilityReason = "integration_does_not_support_replay"
	ReplayAvailabilityReasonAgentVersionDoesNotSupportReplay   ReplayAvailabilityReason = "agent_version_does_not_support_replay"
	ReplayAvailabilityReasonMaxHistoricalDataRetrievalTooLow   ReplayAvailabilityReason = "max_historical_data_retrieval_too_low"
	ReplayAvailabilityReasonConcurrentReplayRunsLimitExhausted ReplayAvailabilityReason = "concurrent_replay_runs_limit_exhausted"
	ReplayAvailabilityReasonUnknownAgentVersion                ReplayAvailabilityReason = "unknown_agent_version"
	ReplayAvailabilityReasonSingleQueryNotSupported            ReplayAvailabilityReason = "single_query_not_supported"
	ReplayAvailabilityReasonCompositeSloNotSupported           ReplayAvailabilityReason = "composite_slo_not_supported"
	ReplayAvailabilityReasonPromqlInGcmNotSupported            ReplayAvailabilityReason = "promql_in_gcm_not_supported"
)

var ErrInvalidReplayAvailabilityReason = errors.New("not a valid ReplayAvailabilityReason")

// ReplayAvailabilityReasonValues returns a list of the values for ReplayAvailabilityReason
func ReplayAvailabilityReasonValues() []ReplayAvailabilityReason {
	return []ReplayAvailabilityReason{
		ReplayAvailabilityReasonDatasourceTypeInvalid,
		ReplayAvailabilityReasonProjectDoesNotExist,
		ReplayAvailabilityReasonDataSourceDoesNotExist,
		ReplayAvailabilityReasonIntegrationDoesNotSupportReplay,
		ReplayAvailabilityReasonAgentVersionDoesNotSupportReplay,
		ReplayAvailabilityReasonMaxHistoricalDataRetrievalTooLow,
		ReplayAvailabilityReasonConcurrentReplayRunsLimitExhausted,
		ReplayAvailabilityReasonUnknownAgentVersion,
		ReplayAvailabilityReasonSingleQueryNotSupported,
		ReplayAvailabilityReasonCompositeSloNotSupported,
		ReplayAvailabilityReasonPromqlInGcmNotSupported,
	}
}

// String implements the Stringer interface.
func (x ReplayAvailabilityReason) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplayAvailabilityReason) IsValid() bool {
	_, err := ParseReplayAvailabilityReason(string(x))
	return err == nil
}

var _ReplayAvailabilityReasonValue = map[string]ReplayAvailabilityReason{
	"datasource_type_invalid":                ReplayAvailabilityReasonDatasourceTypeInvalid,
	"project_does_not_exist":                 ReplayAvailabilityReasonProjectDoesNotExist,
	"data_source_does_not_exist":             ReplayAvailabilityReasonDataSourceDoesNotExist,
	"integration_does_not_support_replay":    ReplayAvailabilityReasonIntegrationDoesNotSupportReplay,
	"agent_version_does_not_support_replay":  ReplayAvailabilityReasonAgentVersionDoesNotSupportReplay,
	"max_historical_data_retrieval_too_low":  ReplayAvailabilityReasonMaxHistoricalDataRetrievalTooLow,
	"concurrent_replay_runs_limit_exhausted": ReplayAvailabilityReasonConcurrentReplayRunsLimitExhausted,
	"unknown_agent_version":                  ReplayAvailabilityReasonUnknownAgentVersion,
	"single_query_not_supported":             ReplayAvailabilityReasonSingleQueryNotSupported,
	"composite_slo_not_supported":            ReplayAvailabilityReasonCompositeSloNotSupported,
	"promql_in_gcm_not_supported":            ReplayAvailabilityReasonPromqlInGcmNotSupported,
}

// ParseReplayAvailabilityReason attempts to convert a string to a ReplayAvailabilityReason.
func ParseReplayAvailabilityReason(name string) (ReplayAvailabilityReason, error) {
	if x, ok := _ReplayAvailabilityReasonValue[name]; ok {
		return x, nil
	}
	return ReplayAvailabilityReason(""), fmt.Errorf("%s is %w", name, ErrInvalidReplayAvailabilityReason)
}

const (
	ReplayCancellationStatusPossible  ReplayCancellationStatus = "possible"
	ReplayCancellationStatusBlocked   ReplayCancellationStatus = "blocked"
	ReplayCancellationStatusRequested ReplayCancellationStatus = "requested"
	ReplayCancellationStatusDenied    ReplayCancellationStatus = "denied"
	ReplayCancellationStatusDone      ReplayCancellationStatus = "done"
)

var ErrInvalidReplayCancellationStatus = errors.New("not a valid ReplayCancellationStatus")

// ReplayCancellationStatusValues returns a list of the values for ReplayCancellationStatus
func ReplayCancellationStatusValues() []ReplayCancellationStatus {
	return []ReplayCancellationStatus{
		ReplayCancellationStatusPossible,
		ReplayCancellationStatusBlocked,
		ReplayCancellationStatusRequested,
		ReplayCancellationStatusDenied,
		ReplayCancellationStatusDone,
	}
}

// String implements the Stringer interface.
func (x ReplayCancellationStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplayCancellationStatus) IsValid() bool {
	_, err := ParseReplayCancellationStatus(string(x))
	return err == nil
}

var _ReplayCancellationStatusValue = map[string]ReplayCancellationStatus{
	"possible":  ReplayCancellationStatusPossible,
	"blocked":   ReplayCancellationStatusBlocked,
	"requested": ReplayCancellationStatusRequested,
	"denied":    ReplayCancellationStatusDenied,
	"done":      ReplayCancellationStatusDone,
}

// ParseReplayCancellationStatus attempts to convert a string to a ReplayCancellationStatus.
func ParseReplayCancellationStatus(name string) (ReplayCancellationStatus, error) {
	if x, ok := _ReplayCancellationStatusValue[name]; ok {
		return x, nil
	}
	return ReplayCancellationStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidReplayCancellationStatus)
}

const (
	ReplayListStatusUnknown    ReplayListStatus = "unknown"
	ReplayListStatusQueued     ReplayListStatus = "queued"
	ReplayListStatusInProgress ReplayListStatus = "in progress"
	ReplayListStatusCompleted  ReplayListStatus = "completed"
	ReplayListStatusFailed     ReplayListStatus = "failed"
	ReplayListStatusCanceled   ReplayListStatus = "canceled"
)

var ErrInvalidReplayListStatus = errors.New("not a valid ReplayListStatus")

// ReplayListStatusValues returns a list of the values for ReplayListStatus
func ReplayListStatusValues() []ReplayListStatus {
	return []ReplayListStatus{
		ReplayListStatusUnknown,
		ReplayListStatusQueued,
		ReplayListStatusInProgress,
		ReplayListStatusCompleted,
		ReplayListStatusFailed,
		ReplayListStatusCanceled,
	}
}

// String implements the Stringer interface.
func (x ReplayListStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplayListStatus) IsValid() bool {
	_, err := ParseReplayListStatus(string(x))
	return err == nil
}

var _ReplayListStatusValue = map[string]ReplayListStatus{
	"unknown":     ReplayListStatusUnknown,
	"queued":      ReplayListStatusQueued,
	"in progress": ReplayListStatusInProgress,
	"completed":   ReplayListStatusCompleted,
	"failed":      ReplayListStatusFailed,
	"canceled":    ReplayListStatusCanceled,
}

// ParseReplayListStatus attempts to convert a string to a ReplayListStatus.
func ParseReplayListStatus(name string) (ReplayListStatus, error) {
	if x, ok := _ReplayListStatusValue[name]; ok {
		return x, nil
	}
	return ReplayListStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidReplayListStatus)
}

const (
	ReplaySourceUser                  ReplaySource = "user"
	ReplaySourceErrorBudgetAdjustment ReplaySource = "error_budget_adjustment"
)

var ErrInvalidReplaySource = errors.New("not a valid ReplaySource")

// ReplaySourceValues returns a list of the values for ReplaySource
func ReplaySourceValues() []ReplaySource {
	return []ReplaySource{
		ReplaySourceUser,
		ReplaySourceErrorBudgetAdjustment,
	}
}

// String implements the Stringer interface.
func (x ReplaySource) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplaySource) IsValid() bool {
	_, err := ParseReplaySource(string(x))
	return err == nil
}

var _ReplaySourceValue = map[string]ReplaySource{
	"user":                    ReplaySourceUser,
	"error_budget_adjustment": ReplaySourceErrorBudgetAdjustment,
}

// ParseReplaySource attempts to convert a string to a ReplaySource.
func ParseReplaySource(name string) (ReplaySource, error) {
	if x, ok := _ReplaySourceValue[name]; ok {
		return x, nil
	}
	return ReplaySource(""), fmt.Errorf("%s is %w", name, ErrInvalidReplaySource)
}

const (
	ReplayTypeReimportAndRecalculation ReplayType = "reimport_and_recalculation"
	ReplayTypeRecalculation            ReplayType = "recalculation"
)

var ErrInvalidReplayType = errors.New("not a valid ReplayType")

// ReplayTypeValues returns a list of the values for ReplayType
func ReplayTypeValues() []ReplayType {
	return []ReplayType{
		ReplayTypeReimportAndRecalculation,
		ReplayTypeRecalculation,
	}
}

// String implements the Stringer interface.
func (x ReplayType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplayType) IsValid() bool {
	_, err := ParseReplayType(string(x))
	return err == nil
}

var _ReplayTypeValue = map[string]ReplayType{
	"reimport_and_recalculation": ReplayTypeReimportAndRecalculation,
	"recalculation":              ReplayTypeRecalculation,
}

// ParseReplayType attempts to convert a string to a ReplayType.
func ParseReplayType(name string) (ReplayType, error) {
	if x, ok := _ReplayTypeValue[name]; ok {
		return x, nil
	}
	return ReplayType(""), fmt.Errorf("%s is %w", name, ErrInvalidReplayType)
}
