// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.4
// Revision: 239df6970e0d16b293dc7407836a48ec13170862
// Build Date: 2026-07-09T20:37:25Z
// Built By: goreleaser

package v1

import (
	"fmt"
	"strings"
)

const (
	DurationUnitMinute DurationUnit = "Minute"
	DurationUnitHour   DurationUnit = "Hour"
	DurationUnitDay    DurationUnit = "Day"
)

var ErrInvalidDurationUnit = fmt.Errorf("not a valid DurationUnit, try [%s]", strings.Join(_DurationUnitNames, ", "))

var _DurationUnitNames = []string{
	string(DurationUnitMinute),
	string(DurationUnitHour),
	string(DurationUnitDay),
}

// DurationUnitNames returns a list of possible string values of DurationUnit.
func DurationUnitNames() []string {
	tmp := make([]string, len(_DurationUnitNames))
	copy(tmp, _DurationUnitNames)
	return tmp
}

// DurationUnitValues returns a list of the values for DurationUnit
func DurationUnitValues() []DurationUnit {
	return []DurationUnit{
		DurationUnitMinute,
		DurationUnitHour,
		DurationUnitDay,
	}
}

// String implements the Stringer interface.
func (x DurationUnit) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DurationUnit) IsValid() bool {
	_, err := ParseDurationUnit(string(x))
	return err == nil
}

var _DurationUnitValue = map[string]DurationUnit{
	"Minute": DurationUnitMinute,
	"Hour":   DurationUnitHour,
	"Day":    DurationUnitDay,
}

// ParseDurationUnit attempts to convert a string to a DurationUnit.
func ParseDurationUnit(name string) (DurationUnit, error) {
	if x, ok := _DurationUnitValue[name]; ok {
		return x, nil
	}
	return DurationUnit(""), fmt.Errorf("%s is %w", name, ErrInvalidDurationUnit)
}

const (
	ReplayAvailabilityReasonDatasourceTypeInvalid              ReplayAvailabilityReason = "datasource_type_invalid"
	ReplayAvailabilityReasonProjectDoesNotExist                ReplayAvailabilityReason = "project_does_not_exist"
	ReplayAvailabilityReasonDataSourceDoesNotExist             ReplayAvailabilityReason = "data_source_does_not_exist"
	ReplayAvailabilityReasonIntegrationDoesNotSupportReplay    ReplayAvailabilityReason = "integration_does_not_support_replay"
	ReplayAvailabilityReasonAgentVersionDoesNotSupportReplay   ReplayAvailabilityReason = "agent_version_does_not_support_replay"
	ReplayAvailabilityReasonMaxHistoricalDataRetrievalTooLow   ReplayAvailabilityReason = "max_historical_data_retrieval_too_low"
	ReplayAvailabilityReasonConcurrentReplayRunsLimitExhausted ReplayAvailabilityReason = "concurrent_replay_runs_limit_exhausted"
	ReplayAvailabilityReasonUnknownAgentVersion                ReplayAvailabilityReason = "unknown_agent_version"
	ReplayAvailabilityReasonSingleQueryNotSupported            ReplayAvailabilityReason = "single_query_not_supported"
	ReplayAvailabilityReasonCompositeSloNotSupported           ReplayAvailabilityReason = "composite_slo_not_supported"
	ReplayAvailabilityReasonPromqlInGcmNotSupported            ReplayAvailabilityReason = "promql_in_gcm_not_supported"
)

var ErrInvalidReplayAvailabilityReason = fmt.Errorf("not a valid ReplayAvailabilityReason, try [%s]", strings.Join(_ReplayAvailabilityReasonNames, ", "))

var _ReplayAvailabilityReasonNames = []string{
	string(ReplayAvailabilityReasonDatasourceTypeInvalid),
	string(ReplayAvailabilityReasonProjectDoesNotExist),
	string(ReplayAvailabilityReasonDataSourceDoesNotExist),
	string(ReplayAvailabilityReasonIntegrationDoesNotSupportReplay),
	string(ReplayAvailabilityReasonAgentVersionDoesNotSupportReplay),
	string(ReplayAvailabilityReasonMaxHistoricalDataRetrievalTooLow),
	string(ReplayAvailabilityReasonConcurrentReplayRunsLimitExhausted),
	string(ReplayAvailabilityReasonUnknownAgentVersion),
	string(ReplayAvailabilityReasonSingleQueryNotSupported),
	string(ReplayAvailabilityReasonCompositeSloNotSupported),
	string(ReplayAvailabilityReasonPromqlInGcmNotSupported),
}

// ReplayAvailabilityReasonNames returns a list of possible string values of ReplayAvailabilityReason.
func ReplayAvailabilityReasonNames() []string {
	tmp := make([]string, len(_ReplayAvailabilityReasonNames))
	copy(tmp, _ReplayAvailabilityReasonNames)
	return tmp
}

// ReplayAvailabilityReasonValues returns a list of the values for ReplayAvailabilityReason
func ReplayAvailabilityReasonValues() []ReplayAvailabilityReason {
	return []ReplayAvailabilityReason{
		ReplayAvailabilityReasonDatasourceTypeInvalid,
		ReplayAvailabilityReasonProjectDoesNotExist,
		ReplayAvailabilityReasonDataSourceDoesNotExist,
		ReplayAvailabilityReasonIntegrationDoesNotSupportReplay,
		ReplayAvailabilityReasonAgentVersionDoesNotSupportReplay,
		ReplayAvailabilityReasonMaxHistoricalDataRetrievalTooLow,
		ReplayAvailabilityReasonConcurrentReplayRunsLimitExhausted,
		ReplayAvailabilityReasonUnknownAgentVersion,
		ReplayAvailabilityReasonSingleQueryNotSupported,
		ReplayAvailabilityReasonCompositeSloNotSupported,
		ReplayAvailabilityReasonPromqlInGcmNotSupported,
	}
}

// String implements the Stringer interface.
func (x ReplayAvailabilityReason) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplayAvailabilityReason) IsValid() bool {
	_, err := ParseReplayAvailabilityReason(string(x))
	return err == nil
}

var _ReplayAvailabilityReasonValue = map[string]ReplayAvailabilityReason{
	"datasource_type_invalid":                ReplayAvailabilityReasonDatasourceTypeInvalid,
	"project_does_not_exist":                 ReplayAvailabilityReasonProjectDoesNotExist,
	"data_source_does_not_exist":             ReplayAvailabilityReasonDataSourceDoesNotExist,
	"integration_does_not_support_replay":    ReplayAvailabilityReasonIntegrationDoesNotSupportReplay,
	"agent_version_does_not_support_replay":  ReplayAvailabilityReasonAgentVersionDoesNotSupportReplay,
	"max_historical_data_retrieval_too_low":  ReplayAvailabilityReasonMaxHistoricalDataRetrievalTooLow,
	"concurrent_replay_runs_limit_exhausted": ReplayAvailabilityReasonConcurrentReplayRunsLimitExhausted,
	"unknown_agent_version":                  ReplayAvailabilityReasonUnknownAgentVersion,
	"single_query_not_supported":             ReplayAvailabilityReasonSingleQueryNotSupported,
	"composite_slo_not_supported":            ReplayAvailabilityReasonCompositeSloNotSupported,
	"promql_in_gcm_not_supported":            ReplayAvailabilityReasonPromqlInGcmNotSupported,
}

// ParseReplayAvailabilityReason attempts to convert a string to a ReplayAvailabilityReason.
func ParseReplayAvailabilityReason(name string) (ReplayAvailabilityReason, error) {
	if x, ok := _ReplayAvailabilityReasonValue[name]; ok {
		return x, nil
	}
	return ReplayAvailabilityReason(""), fmt.Errorf("%s is %w", name, ErrInvalidReplayAvailabilityReason)
}

const (
	ReplayCancellationStatusPossible  ReplayCancellationStatus = "possible"
	ReplayCancellationStatusBlocked   ReplayCancellationStatus = "blocked"
	ReplayCancellationStatusRequested ReplayCancellationStatus = "requested"
	ReplayCancellationStatusDenied    ReplayCancellationStatus = "denied"
	ReplayCancellationStatusDone      ReplayCancellationStatus = "done"
)

var ErrInvalidReplayCancellationStatus = fmt.Errorf("not a valid ReplayCancellationStatus, try [%s]", strings.Join(_ReplayCancellationStatusNames, ", "))

var _ReplayCancellationStatusNames = []string{
	string(ReplayCancellationStatusPossible),
	string(ReplayCancellationStatusBlocked),
	string(ReplayCancellationStatusRequested),
	string(ReplayCancellationStatusDenied),
	string(ReplayCancellationStatusDone),
}

// ReplayCancellationStatusNames returns a list of possible string values of ReplayCancellationStatus.
func ReplayCancellationStatusNames() []string {
	tmp := make([]string, len(_ReplayCancellationStatusNames))
	copy(tmp, _ReplayCancellationStatusNames)
	return tmp
}

// ReplayCancellationStatusValues returns a list of the values for ReplayCancellationStatus
func ReplayCancellationStatusValues() []ReplayCancellationStatus {
	return []ReplayCancellationStatus{
		ReplayCancellationStatusPossible,
		ReplayCancellationStatusBlocked,
		ReplayCancellationStatusRequested,
		ReplayCancellationStatusDenied,
		ReplayCancellationStatusDone,
	}
}

// String implements the Stringer interface.
func (x ReplayCancellationStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplayCancellationStatus) IsValid() bool {
	_, err := ParseReplayCancellationStatus(string(x))
	return err == nil
}

var _ReplayCancellationStatusValue = map[string]ReplayCancellationStatus{
	"possible":  ReplayCancellationStatusPossible,
	"blocked":   ReplayCancellationStatusBlocked,
	"requested": ReplayCancellationStatusRequested,
	"denied":    ReplayCancellationStatusDenied,
	"done":      ReplayCancellationStatusDone,
}

// ParseReplayCancellationStatus attempts to convert a string to a ReplayCancellationStatus.
func ParseReplayCancellationStatus(name string) (ReplayCancellationStatus, error) {
	if x, ok := _ReplayCancellationStatusValue[name]; ok {
		return x, nil
	}
	return ReplayCancellationStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidReplayCancellationStatus)
}

const (
	ReplayListStatusUnknown    ReplayListStatus = "unknown"
	ReplayListStatusQueued     ReplayListStatus = "queued"
	ReplayListStatusInProgress ReplayListStatus = "in progress"
	ReplayListStatusCompleted  ReplayListStatus = "completed"
	ReplayListStatusFailed     ReplayListStatus = "failed"
	ReplayListStatusCanceled   ReplayListStatus = "canceled"
)

var ErrInvalidReplayListStatus = fmt.Errorf("not a valid ReplayListStatus, try [%s]", strings.Join(_ReplayListStatusNames, ", "))

var _ReplayListStatusNames = []string{
	string(ReplayListStatusUnknown),
	string(ReplayListStatusQueued),
	string(ReplayListStatusInProgress),
	string(ReplayListStatusCompleted),
	string(ReplayListStatusFailed),
	string(ReplayListStatusCanceled),
}

// ReplayListStatusNames returns a list of possible string values of ReplayListStatus.
func ReplayListStatusNames() []string {
	tmp := make([]string, len(_ReplayListStatusNames))
	copy(tmp, _ReplayListStatusNames)
	return tmp
}

// ReplayListStatusValues returns a list of the values for ReplayListStatus
func ReplayListStatusValues() []ReplayListStatus {
	return []ReplayListStatus{
		ReplayListStatusUnknown,
		ReplayListStatusQueued,
		ReplayListStatusInProgress,
		ReplayListStatusCompleted,
		ReplayListStatusFailed,
		ReplayListStatusCanceled,
	}
}

// String implements the Stringer interface.
func (x ReplayListStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplayListStatus) IsValid() bool {
	_, err := ParseReplayListStatus(string(x))
	return err == nil
}

var _ReplayListStatusValue = map[string]ReplayListStatus{
	"unknown":     ReplayListStatusUnknown,
	"queued":      ReplayListStatusQueued,
	"in progress": ReplayListStatusInProgress,
	"completed":   ReplayListStatusCompleted,
	"failed":      ReplayListStatusFailed,
	"canceled":    ReplayListStatusCanceled,
}

// ParseReplayListStatus attempts to convert a string to a ReplayListStatus.
func ParseReplayListStatus(name string) (ReplayListStatus, error) {
	if x, ok := _ReplayListStatusValue[name]; ok {
		return x, nil
	}
	return ReplayListStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidReplayListStatus)
}

const (
	ReplaySourceUser                  ReplaySource = "user"
	ReplaySourceErrorBudgetAdjustment ReplaySource = "error_budget_adjustment"
)

var ErrInvalidReplaySource = fmt.Errorf("not a valid ReplaySource, try [%s]", strings.Join(_ReplaySourceNames, ", "))

var _ReplaySourceNames = []string{
	string(ReplaySourceUser),
	string(ReplaySourceErrorBudgetAdjustment),
}

// ReplaySourceNames returns a list of possible string values of ReplaySource.
func ReplaySourceNames() []string {
	tmp := make([]string, len(_ReplaySourceNames))
	copy(tmp, _ReplaySourceNames)
	return tmp
}

// ReplaySourceValues returns a list of the values for ReplaySource
func ReplaySourceValues() []ReplaySource {
	return []ReplaySource{
		ReplaySourceUser,
		ReplaySourceErrorBudgetAdjustment,
	}
}

// String implements the Stringer interface.
func (x ReplaySource) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplaySource) IsValid() bool {
	_, err := ParseReplaySource(string(x))
	return err == nil
}

var _ReplaySourceValue = map[string]ReplaySource{
	"user":                    ReplaySourceUser,
	"error_budget_adjustment": ReplaySourceErrorBudgetAdjustment,
}

// ParseReplaySource attempts to convert a string to a ReplaySource.
func ParseReplaySource(name string) (ReplaySource, error) {
	if x, ok := _ReplaySourceValue[name]; ok {
		return x, nil
	}
	return ReplaySource(""), fmt.Errorf("%s is %w", name, ErrInvalidReplaySource)
}

const (
	ReplayTypeReimportAndRecalculation ReplayType = "reimport_and_recalculation"
	ReplayTypeRecalculation            ReplayType = "recalculation"
)

var ErrInvalidReplayType = fmt.Errorf("not a valid ReplayType, try [%s]", strings.Join(_ReplayTypeNames, ", "))

var _ReplayTypeNames = []string{
	string(ReplayTypeReimportAndRecalculation),
	string(ReplayTypeRecalculation),
}

// ReplayTypeNames returns a list of possible string values of ReplayType.
func ReplayTypeNames() []string {
	tmp := make([]string, len(_ReplayTypeNames))
	copy(tmp, _ReplayTypeNames)
	return tmp
}

// ReplayTypeValues returns a list of the values for ReplayType
func ReplayTypeValues() []ReplayType {
	return []ReplayType{
		ReplayTypeReimportAndRecalculation,
		ReplayTypeRecalculation,
	}
}

// String implements the Stringer interface.
func (x ReplayType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReplayType) IsValid() bool {
	_, err := ParseReplayType(string(x))
	return err == nil
}

var _ReplayTypeValue = map[string]ReplayType{
	"reimport_and_recalculation": ReplayTypeReimportAndRecalculation,
	"recalculation":              ReplayTypeRecalculation,
}

// ParseReplayType attempts to convert a string to a ReplayType.
func ParseReplayType(name string) (ReplayType, error) {
	if x, ok := _ReplayTypeValue[name]; ok {
		return x, nil
	}
	return ReplayType(""), fmt.Errorf("%s is %w", name, ErrInvalidReplayType)
}
