name: checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    name: Run all checks for static analysis
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Set up prerequisites - node and yarn
        uses: actions/setup-node@v3
      - name: Set up yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          make install/yarn
      - name: Run spell and markdown checkers
        run: |
          make check/spell check/trailing check/markdown
      - name: Check generated code
        run: |
          make check/generate
      - name: Run go vet
        run: |
          make check/vet
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
      - name: Run renovate-config-validator
        run: |
          make check/renovate
