name: End-to-end tests
on:
  workflow_call:
    inputs:
      clientId:
        description: Client ID to use for authentication
        required: true
        type: string
      oktaOrgUrl:
        description: Okta organization URL
        required: false
        type: string
      oktaAuthServer:
        description: Okta authentication server identifier
        required: false
        type: string
      ref:
        description: Reference branch, tag or commit SHA to checkout
        required: false
        type: string
        default: main
      sequentialApplyAndDelete:
        description: Whether to perform apply/delete requests sequentially
        required: false
        type: boolean
        default: true
      httpRequestTimeout:
        description: Timeout for every HTTP request to the Nobl9 API
        required: false
        type: string
        default: 1m
    secrets:
      clientSecret:
        description: Client secret to use for authentication
        required: true
jobs:
  test:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          repository: nobl9/nobl9-go
          ref: ${{ inputs.ref }}
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false
      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: make test/e2e
        env:
          NOBL9_SDK_CLIENT_ID: ${{ inputs.clientId }}
          NOBL9_SDK_CLIENT_SECRET: ${{ secrets.clientSecret }}
          NOBL9_SDK_OKTA_ORG_URL: ${{ inputs.oktaOrgUrl }}
          NOBL9_SDK_OKTA_AUTH_SERVER: ${{ inputs.oktaAuthServer }}
          NOBL9_SDK_NO_CONFIG_FILE: true
          NOBL9_SDK_TEST_RUN_SEQUENTIAL_APPLY_AND_DELETE: ${{ inputs.sequentialApplyAndDelete }}
          NOBL9_SDK_TIMEOUT: ${{ inputs.httpRequestTimeout }}
