name: checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false
      - name: Run unit tests
        run: |
          make test
