name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Run unit tests
        run: go test -race -cover ./... ./docs/mock_example
