name: Vulnerabilities
on:
  push:
    branches:
      - main
  schedule:
    # Run at 8:00 AM every weekday.
    - cron:  '0 8 * * 1-5'
jobs:
  scan:
    name: Run Golang vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Golang Vulncheck
        run: make check/vulns
