name: Vulnerabilities
on:
  push:
    branches:
      - main
jobs:
  scan:
    name: Run Golang vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Golang Vulncheck
        run: make check/vulns
