// Code generated by ifacemaker; DO NOT EDIT.

package v1

import (
	"context"

	v1alphaReport "github.com/nobl9/nobl9-go/manifest/v1alpha/report"
)

type Endpoints interface {
	// GetUsageSummary returns resource usage and quota status for the current organization.
	GetUsageSummary(ctx context.Context) (response UsageSummary, err error)
	// GetReliabilityRollup returns data for a saved Reliability Roll-up report identified by its metadata name.
	GetReliabilityRollup(ctx context.Context, name string, params ReliabilityRollupRequest) (response ReliabilityRollup, err error)
	// GenerateReliabilityRollup returns data for a Report manifest without saving or updating a report.
	GenerateReliabilityRollup(ctx context.Context, report v1alphaReport.Report, params ReliabilityRollupRequest) (response ReliabilityRollup, err error)
}
