package v1

import (
	"time"

	"github.com/nobl9/nobl9-go/manifest/v1alpha"
	v1alphaSLO "github.com/nobl9/nobl9-go/manifest/v1alpha/slo"
)

type UsageSummary struct {
	Metadata     UsageSummaryMetadata `json:"metadata"`
	UsageSummary ResourceUsage        `json:"usageSummary"`
}

type UsageSummaryMetadata struct {
	Tier           Tier   `json:"tier"`
	GeneratedAt    string `json:"generatedAt"`
	LicenseEndDate string `json:"licenseEndDate"`
}

type Tier struct {
	Name string `json:"name"`
}

type ResourceUsage struct {
	SLOs                   Usage `json:"slos"`
	SLOUnits               Usage `json:"sloUnits"`
	CompositeSLOComponents Usage `json:"compositeSloComponents"`
	DataSources            Usage `json:"dataSources"`
	Users                  Usage `json:"users"`
}

type Usage struct {
	CurrentUsage     float64  `json:"currentUsage"`
	PeakUsage        float64  `json:"peakUsage"`
	ContractedAmount *float64 `json:"contractedAmount,omitempty"`
	// QuotaStatus is nil when the quota has not been reached.
	QuotaStatus *string `json:"quotaStatus"`
}

// ReliabilityRollup contains the report hierarchy, reliability gauges, and summary statistics.
// A nil gauge indicates that reliability data is unavailable.
type ReliabilityRollup struct {
	TotalSLOs                 int                      `json:"totalSlos"`
	TotalReliabilityGauge     *float64                 `json:"totalReliabilityGauge"`
	ServiceStats              ServiceStats             `json:"serviceStats"`
	ReliabilityGaugeStructure []Folder                 `json:"reliabilityGaugeStructure"`
	IsAutoGenerated           bool                     `json:"isAutoGenerated"`
	SLOStats                  SLOStats                 `json:"sloStats"`
	FolderStats               FolderStats              `json:"folderStats"`
	Summary                   ReliabilityRollupSummary `json:"summary"`
}

type ServiceStats struct {
	ServiceCount          int `json:"serviceCount"`
	ExhaustedServiceCount int `json:"exhaustedServiceCount"`
	HealthyServiceCount   int `json:"healthyServiceCount"`
}

type SLOStats struct {
	Healthy      int `json:"healthy"`
	Exhausted    int `json:"exhausted"`
	NotAvailable int `json:"notAvailable"`
}

type FolderStats struct {
	Total     int `json:"total"`
	Healthy   int `json:"healthy"`
	Exhausted int `json:"exhausted"`
}

type ReliabilityRollupSummary struct {
	RollupPeriod     RollupPeriod        `json:"rollupPeriod"`
	ReliabilityScore ValueWithTrend      `json:"reliabilityScore"`
	SLOsOverBudget   CountValueWithTrend `json:"slosOverBudget"`
	SLOsWithinBudget CountValueWithTrend `json:"slosWithinBudget"`
	SLOsTotal        int                 `json:"slosTotal"`
	LeastReliable    []FolderSummary     `json:"leastReliable"`
	MostReliable     []FolderSummary     `json:"mostReliable"`
}

type RollupPeriod struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

// ValueWithTrend contains a nullable score and its difference from the comparison period.
// Trend is nil when no comparison period was requested or comparison data is unavailable.
type ValueWithTrend struct {
	Value *float64 `json:"value"`
	Trend *float64 `json:"trend"`
}

type CountValueWithTrend struct {
	Value *float64 `json:"value"`
	Trend *float64 `json:"trend"`
	Count int      `json:"count"`
}

type FolderSummary struct {
	Metadata         FolderMetadata `json:"metadata"`
	ReliabilityScore ValueWithTrend `json:"reliabilityScore"`
}

// Folder holds child folders or leaf SLOs in an automatic or custom report hierarchy.
type Folder struct {
	Metadata         FolderMetadata `json:"metadata"`
	ReliabilityGauge *float64       `json:"reliabilityGauge"`
	Children         []Folder       `json:"children,omitempty"`
	SLOs             []SLO          `json:"slos,omitempty"`
}

type FolderMetadata struct {
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
	Project     string `json:"project,omitempty"`
}

type SLO struct {
	Metadata             SLOMetadata           `json:"metadata"`
	SyntheticProjectName string                `json:"syntheticProjectName"`
	Objectives           []Objective           `json:"objectives"`
	TimeWindow           v1alphaSLO.TimeWindow `json:"timeWindow"`
	ReliabilityGauge     *float64              `json:"reliabilityGauge"`
	IsComposite          bool                  `json:"isComposite"`
	IsCompositeV2        bool                  `json:"isCompositeV2"`
}

type SLOMetadata struct {
	Name        string         `json:"name"`
	DisplayName string         `json:"displayName"`
	Project     string         `json:"project"`
	Labels      v1alpha.Labels `json:"labels"`
}

type Objective struct {
	Name             string   `json:"name"`
	DisplayName      string   `json:"displayName"`
	Value            float64  `json:"value"`
	Target           *float64 `json:"target"`
	TimeSliceTarget  *float64 `json:"timeSliceTarget"`
	Operator         *string  `json:"op"`
	ReliabilityGauge *float64 `json:"reliabilityGauge"`
	IsRawMetric      bool     `json:"isRawMetric"`
	IsIncremental    bool     `json:"isIncremental"`
	IsCompositeV2    bool     `json:"isCompositeV2"`
	IsPrimary        bool     `json:"isPrimary"`
}
