// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package report

import (
	"fmt"
	"strings"
)

const (
	// ReliabilityScoreTypeSLOTimeWindow is a ReliabilityScoreType of type SLOTimeWindow.
	ReliabilityScoreTypeSLOTimeWindow ReliabilityScoreType = "SLOTimeWindow"
	// ReliabilityScoreTypeReportTimeFrame is a ReliabilityScoreType of type ReportTimeFrame.
	ReliabilityScoreTypeReportTimeFrame ReliabilityScoreType = "ReportTimeFrame"
)

var ErrInvalidReliabilityScoreType = fmt.Errorf("not a valid ReliabilityScoreType, try [%s]", strings.Join(_ReliabilityScoreTypeNames, ", "))

var _ReliabilityScoreTypeNames = []string{
	string(ReliabilityScoreTypeSLOTimeWindow),
	string(ReliabilityScoreTypeReportTimeFrame),
}

// ReliabilityScoreTypeNames returns a list of possible string values of ReliabilityScoreType.
func ReliabilityScoreTypeNames() []string {
	tmp := make([]string, len(_ReliabilityScoreTypeNames))
	copy(tmp, _ReliabilityScoreTypeNames)
	return tmp
}

// ReliabilityScoreTypeValues returns a list of the values for ReliabilityScoreType
func ReliabilityScoreTypeValues() []ReliabilityScoreType {
	return []ReliabilityScoreType{
		ReliabilityScoreTypeSLOTimeWindow,
		ReliabilityScoreTypeReportTimeFrame,
	}
}

// String implements the Stringer interface.
func (x ReliabilityScoreType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ReliabilityScoreType) IsValid() bool {
	_, err := ParseReliabilityScoreType(string(x))
	return err == nil
}

var _ReliabilityScoreTypeValue = map[string]ReliabilityScoreType{
	"SLOTimeWindow":   ReliabilityScoreTypeSLOTimeWindow,
	"slotimewindow":   ReliabilityScoreTypeSLOTimeWindow,
	"ReportTimeFrame": ReliabilityScoreTypeReportTimeFrame,
	"reporttimeframe": ReliabilityScoreTypeReportTimeFrame,
}

// ParseReliabilityScoreType attempts to convert a string to a ReliabilityScoreType.
func ParseReliabilityScoreType(name string) (ReliabilityScoreType, error) {
	if x, ok := _ReliabilityScoreTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ReliabilityScoreTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ReliabilityScoreType(""), fmt.Errorf("%s is %w", name, ErrInvalidReliabilityScoreType)
}
